type ItemInformation = {
    price: number;
    level: number;
    category: string;
}

const itemPrices = {
    "Vanilla ice cream": {price: 172.8, level: 0, category: ""},
    "Top hat": {price: 619.2, level: 0, category: ""},
    "Pomegranate cake": {price: 316.8, level: 0, category: ""},
    "Strawberry jam": {price: 270.0, level: 0, category: ""},
    "Cream cake": {price: 219.6, level: 0, category: ""},
    "Caffè mocha": {price: 291.6, level: 0, category: ""},
    "Plain cupcake": {price: 280.8, level: 0, category: ""},
    "Mango juice": {price: 230.4, level: 0, category: ""},
    "Cream": {price: 50.4, level: 0, category: ""},
    "Sesame brittle": {price: 270.0, level: 0, category: ""},
    "Egg sushi": {price: 550.8, level: 0, category: ""},
    "Potted plant": {price: 151.2, level: 0, category: ""},
    "Pig feed": {price: 14.4, level: 0, category: ""},
    "Falafel": {price: 226.8, level: 0, category: ""},
    "Spicy pasta": {price: 576.0, level: 0, category: ""},
    "Honey soap": {price: 327.6, level: 0, category: ""},
    "Cabbage soup": {price: 270.0, level: 0, category: ""},
    "Flower pendant": {price: 698.4, level: 0, category: ""},
    "Peanut Noodles": {price: 597.6, level: 0, category: ""},
    "Silver ore": {price: 18.0, level: 0, category: ""},
    "Honey peanuts": {price: 468.0, level: 0, category: ""},
    "Veggie Platter": {price: 266.4, level: 0, category: ""},
    "Cotton shirt": {price: 241.2, level: 0, category: ""},
    "Mayonnaise": {price: 367.2, level: 0, category: ""},
    "Orange salad": {price: 558.0, level: 0, category: ""},
    "Fish burger": {price: 226.8, level: 0, category: ""},
    "Fish taco": {price: 392.4, level: 0, category: ""},
    "Peanut Butter and Jelly Sandwich": {price: 601.2, level: 0, category: ""},
    "Breakfast bowl": {price: 604.8, level: 0, category: ""},
    "Tomato juice": {price: 162.0, level: 0, category: ""},
    "Peach jam": {price: 464.4, level: 0, category: ""},
    "Iced tea": {price: 252.0, level: 0, category: ""},
    "Bacon and eggs": {price: 201.6, level: 0, category: ""},
    "Pickles": {price: 270.0, level: 0, category: ""},
    "Feta pie": {price: 223.2, level: 0, category: ""},
    "Hummus wrap": {price: 374.4, level: 0, category: ""},
    "Spicy pizza": {price: 226.8, level: 0, category: ""},
    "Cherry juice": {price: 216.0, level: 0, category: ""},
    "Chocolate roll": {price: 604.8, level: 0, category: ""},
    "Orange juice": {price: 234.0, level: 0, category: ""},
    "Red berry cake": {price: 255.6, level: 0, category: ""},
    "Chocolate popcorn": {price: 248.4, level: 0, category: ""},
    "Marmalade": {price: 457.2, level: 0, category: ""},
    "Hot dog": {price: 370.8, level: 0, category: ""},
    "Peanut Butter Milkshake": {price: 619.2, level: 0, category: ""},
    "Pineapple cake": {price: 259.2, level: 0, category: ""},
    "Cotton candy": {price: 226.8, level: 0, category: ""},
    "Green smoothie": {price: 320.4, level: 0, category: ""},
    "Vanilla milkshake": {price: 673.2, level: 0, category: ""},
    "Mushroom soup": {price: 176.4, level: 0, category: ""},
    "Coal": {price: 10.8, level: 0, category: ""},
    "Espresso": {price: 248.4, level: 0, category: ""},
    "Fish pie": {price: 226.8, level: 0, category: ""},
    "Tropical smoothie": {price: 475.2, level: 0, category: ""},
    "Grilled onion": {price: 190.8, level: 0, category: ""},
    "Cheese omelet": {price: 464.4, level: 0, category: ""},
    "Rice Omelet": {price: 572.4, level: 0, category: ""},
    "Egg sandwich": {price: 583.2, level: 0, category: ""},
    "Gnocchi": {price: 475.2, level: 0, category: ""},
    "Pineapple coconut bars": {price: 284.4, level: 0, category: ""},
    "Hamburger": {price: 180.0, level: 0, category: ""},
    "Shepherds pie": {price: 280.8, level: 0, category: ""},
    "Peach ice cream": {price: 450.0, level: 0, category: ""},
    "Coleslaw": {price: 468.0, level: 0, category: ""},
    "Lollipop": {price: 342.0, level: 0, category: ""},
    "Salsa": {price: 252.0, level: 0, category: ""},
    "Hot chocolate": {price: 316.8, level: 0, category: ""},
    "Goat cheese toast": {price: 302.4, level: 0, category: ""},
    "Winter veggies": {price: 198.0, level: 0, category: ""},
    "Watermelon juice": {price: 108.0, level: 0, category: ""},
    "Goat feed": {price: 14.4, level: 0, category: ""},
    "Stuffed pepppers": {price: 352.8, level: 0, category: ""},
    "Spring omelet": {price: 230.4, level: 0, category: ""},
    "Flower crown": {price: 331.2, level: 0, category: ""},
    "Cookie cupcake": {price: 712.8, level: 0, category: ""},
    "Passion fruit pie": {price: 111.6, level: 0, category: ""},
    "Flower shawl": {price: 295.2, level: 0, category: ""},
    "Spicy fish": {price: 543.6, level: 0, category: ""},
    "Apple pie": {price: 270.0, level: 0, category: ""},
    "Honey apple cake": {price: 482.4, level: 0, category: ""},
    "Lobster soup": {price: 612.0, level: 0, category: ""},
    "Caffè latte": {price: 219.6, level: 0, category: ""},
    "Violet dress": {price: 327.6, level: 0, category: ""},
    "Diamond ring": {price: 824.4, level: 0, category: ""},
    "Bacon Fries": {price: 302.4, level: 0, category: ""},
    "Guava juice": {price: 252.0, level: 0, category: ""},
    "Sweet porridge": {price: 460.8, level: 0, category: ""},
    "Fruit salad": {price: 597.6, level: 0, category: ""},
    "Lobster skewer": {price: 417.6, level: 0, category: ""},
    "Bacon toast": {price: 648.0, level: 0, category: ""},
    "Asparagus quiche": {price: 302.4, level: 0, category: ""},
    "Honey toast": {price: 255.6, level: 0, category: ""},
    "Baked potato": {price: 298.8, level: 0, category: ""},
    "Carrot cake": {price: 165.6, level: 0, category: ""},
    "Cherry popsicle": {price: 352.8, level: 0, category: ""},
    "Red scarf": {price: 288.0, level: 0, category: ""},
    "Guava compote": {price: 421.2, level: 0, category: ""},
    "Pizza": {price: 190.8, level: 0, category: ""},
    "Tofu stir fry": {price: 306.0, level: 0, category: ""},
    "Tomato soup": {price: 478.8, level: 0, category: ""},
    "Samosa": {price: 223.2, level: 0, category: ""},
    "Raspberry mocha": {price: 259.2, level: 0, category: ""},
    "Plain waffles": {price: 198.0, level: 0, category: ""},
    "Lemon cake": {price: 896.4, level: 0, category: ""},
    "Honey tea": {price: 313.2, level: 0, category: ""},
    "Popcorn": {price: 32.4, level: 0, category: ""},
    "Tea pot": {price: 219.6, level: 0, category: ""},
    "Blanket": {price: 1098.0, level: 0, category: ""},
    "Chickpea stew": {price: 284.4, level: 0, category: ""},
    "Apple porridge": {price: 522.0, level: 0, category: ""},
    "Chocolate waffles": {price: 637.2, level: 0, category: ""},
    "Strawberry cake": {price: 316.8, level: 0, category: ""},
    "Cookie": {price: 104.4, level: 0, category: ""},
    "Sheep feed": {price: 14.4, level: 0, category: ""},
    "Fish and chips": {price: 244.8, level: 0, category: ""},
    "Colourful omelet": {price: 136.8, level: 0, category: ""},
    "Plain yogurt": {price: 234.0, level: 0, category: ""},
    "Grape jam": {price: 162.0, level: 0, category: ""},
    "Strawberry yogurt": {price: 529.2, level: 0, category: ""},
    "Apple Ginger Tea": {price: 169.2, level: 0, category: ""},
    "Toffee": {price: 176.4, level: 0, category: ""},
    "Mushroom pot pie": {price: 162.0, level: 0, category: ""},
    "Rice noodles": {price: 100.8, level: 0, category: ""},
    "Candy bouquet": {price: 554.4, level: 0, category: ""},
    "Mint tea": {price: 255.6, level: 0, category: ""},
    "Wheat Bundle": {price: 50.4, level: 0, category: ""},
    "Pumpkin soup": {price: 392.4, level: 0, category: ""},
    "Chili popcorn": {price: 122.4, level: 0, category: ""},
    "Mixed smoothie": {price: 504.0, level: 0, category: ""},
    "Bell Pepper Soup": {price: 439.2, level: 0, category: ""},
    "Pomegranate tea": {price: 313.2, level: 0, category: ""},
    "Summer rolls": {price: 316.8, level: 0, category: ""},
    "Exfoliating soap": {price: 363.6, level: 0, category: ""},
    "Cheesecake": {price: 284.4, level: 0, category: ""},
    "Cloche hat": {price: 468.0, level: 0, category: ""},
    "Passion fruit jam": {price: 118.8, level: 0, category: ""},
    "Fruit cake": {price: 450.0, level: 0, category: ""},
    "Cucumber sandwich": {price: 464.4, level: 0, category: ""},
    "Banana split": {price: 403.2, level: 0, category: ""},
    "Iced banana latte": {price: 277.2, level: 0, category: ""},
    "Onion soup": {price: 327.6, level: 0, category: ""},
    "Passion fruit juice": {price: 64.8, level: 0, category: ""},
    "Snack mix": {price: 309.6, level: 0, category: ""},
    "Clay mug": {price: 212.4, level: 0, category: ""},
    "Summer salad": {price: 554.4, level: 0, category: ""},
    "Soy sauce": {price: 154.8, level: 0, category: ""},
    "Fish skewer": {price: 176.4, level: 0, category: ""},
    "Tart dressing": {price: 288.0, level: 0, category: ""},
    "Lemon tea": {price: 241.2, level: 0, category: ""},
    "Fried candy bar": {price: 658.8, level: 0, category: ""},
    "Chili stew": {price: 370.8, level: 0, category: ""},
    "Strawberry candle": {price: 370.8, level: 0, category: ""},
    "Fresh porridge": {price: 435.6, level: 0, category: ""},
    "Gold bar": {price: 180.0, level: 0, category: ""},
    "Tropical cupcake": {price: 572.4, level: 0, category: ""},
    "Veggie bouquet": {price: 352.8, level: 0, category: ""},
    "Tropical yogurt": {price: 457.2, level: 0, category: ""},
    "Bacon pie": {price: 219.6, level: 0, category: ""},
    "Goat cheese": {price: 162.0, level: 0, category: ""},
    "Carrot juice": {price: 46.8, level: 0, category: ""},
    "Brown sugar": {price: 32.4, level: 0, category: ""},
    "Nachos": {price: 432.0, level: 0, category: ""},
    "Bracelet": {price: 514.8, level: 0, category: ""},
    "Beetroot salad": {price: 234.0, level: 0, category: ""},
    "Berry smoothie": {price: 547.2, level: 0, category: ""},
    "Silver bar": {price: 147.6, level: 0, category: ""},
    "Chocolate fondue": {price: 626.4, level: 0, category: ""},
    "Tomato sauce": {price: 230.4, level: 0, category: ""},
    "Pillow": {price: 676.8, level: 0, category: ""},
    "Blackberry jam": {price: 388.8, level: 0, category: ""},
    "Crunchy donut": {price: 594.0, level: 0, category: ""},
    "Chocolate cake": {price: 320.4, level: 0, category: ""},
    "Pumpkin pie": {price: 158.4, level: 0, category: ""},
    "Potato soup": {price: 255.6, level: 0, category: ""},
    "Butter": {price: 82.8, level: 0, category: ""},
    "Lemon pie": {price: 446.4, level: 0, category: ""},
    "Coconut ice cream": {price: 320.4, level: 0, category: ""},
    "Mushroom pasta": {price: 280.8, level: 0, category: ""},
    "Pancake": {price: 108.0, level: 0, category: ""},
    "Breakfast waffles": {price: 424.8, level: 0, category: ""},
    "Iron ore": {price: 14.4, level: 0, category: ""},
    "Pasta carbonara": {price: 410.4, level: 0, category: ""},
    "Onion dog": {price: 306.0, level: 0, category: ""},
    "Lemon candle": {price: 457.2, level: 0, category: ""},
    "Guava cupcake": {price: 583.2, level: 0, category: ""},
    "Frutti di mare pizza": {price: 403.2, level: 0, category: ""},
    "Green tea": {price: 241.2, level: 0, category: ""},
    "Bacon donut": {price: 388.8, level: 0, category: ""},
    "Floral candle": {price: 442.8, level: 0, category: ""},
    "Mushroom Salad": {price: 216.0, level: 0, category: ""},
    "Filled donut": {price: 403.2, level: 0, category: ""},
    "Olive dip": {price: 468.0, level: 0, category: ""},
    "Gracious bouquet": {price: 500.4, level: 0, category: ""},
    "Rustic bouquet": {price: 208.8, level: 0, category: ""},
    "Lemon curd": {price: 378.0, level: 0, category: ""},
    "Black sesame smoothie": {price: 313.2, level: 0, category: ""},
    "Chili poppers": {price: 406.8, level: 0, category: ""},
    "Cherry jam": {price: 334.8, level: 0, category: ""},
    "Sweater": {price: 151.2, level: 0, category: ""},
    "Peach tart": {price: 435.6, level: 0, category: ""},
    "Caramel latte": {price: 345.6, level: 0, category: ""},
    "Gold ore": {price: 21.6, level: 0, category: ""},
    "Winter stew": {price: 295.2, level: 0, category: ""},
    "Soft bouquet": {price: 298.8, level: 0, category: ""},
    "Peanut fudge": {price: 1141.2, level: 0, category: ""},
    "Sesame Ice Cream": {price: 176.4, level: 0, category: ""},
    "Tropical fondue": {price: 417.6, level: 0, category: ""},
    "Apple jam": {price: 219.6, level: 0, category: ""},
    "Cow feed": {price: 14.4, level: 0, category: ""},
    "Banana pancakes": {price: 352.8, level: 0, category: ""},
    "Milk tea": {price: 190.8, level: 0, category: ""},
    "Colorful candles": {price: 324.0, level: 0, category: ""},
    "Wooly chaps": {price: 309.6, level: 0, category: ""},
    "Potato Omelet": {price: 270.0, level: 0, category: ""},
    "Chocolate ice cream": {price: 342.0, level: 0, category: ""},
    "Mint ice cream": {price: 288.0, level: 0, category: ""},
    "Apple juice": {price: 129.6, level: 0, category: ""},
    "Feta salad": {price: 745.2, level: 0, category: ""},
    "Meat Bucket": {price: 72.0, level: 0, category: ""},
    "Refined coal": {price: 108.0, level: 0, category: ""},
    "Canned fish": {price: 471.6, level: 0, category: ""},
    "Mint fudge": {price: 522.0, level: 0, category: ""},
    "Syrup": {price: 90.0, level: 0, category: ""},
    "Plum jam": {price: 385.2, level: 0, category: ""},
    "Seafood salad": {price: 763.2, level: 0, category: ""},
    "Garlic bread": {price: 198.0, level: 0, category: ""},
    "Orange sorbet": {price: 399.6, level: 0, category: ""},
    "Fresh pasta": {price: 43.2, level: 0, category: ""},
    "Rich fudge": {price: 644.4, level: 0, category: ""},
    "Blue woolly hat": {price: 111.6, level: 0, category: ""},
    "Blue sweater": {price: 208.8, level: 0, category: ""},
    "Raspberry jam": {price: 252.0, level: 0, category: ""},
    "Platinum Ore": {price: 32.4, level: 0, category: ""},
    "Fruit sorbet": {price: 518.4, level: 0, category: ""},
    "Blackberry muffin": {price: 226.8, level: 0, category: ""},
    "Chocolate": {price: 460.8, level: 0, category: ""},
    "Mint essential oil": {price: 172.8, level: 0, category: ""},
    "Cotton fabric": {price: 108.0, level: 0, category: ""},
    "Rich soap": {price: 266.4, level: 0, category: ""},
    "Sprinkled donut": {price: 313.2, level: 0, category: ""},
    "Lobster pasta": {price: 637.2, level: 0, category: ""},
    "Chili fudge": {price: 540.0, level: 0, category: ""},
    "Cream donut": {price: 230.4, level: 0, category: ""},
    "Fish soup": {price: 298.8, level: 0, category: ""},
    "Eggplant parmesan": {price: 442.8, level: 0, category: ""},
    "Beeswax": {price: 234.0, level: 0, category: ""},
    "Grilled Asparagus": {price: 486.0, level: 0, category: ""},
    "Strawberry ice cream": {price: 331.2, level: 0, category: ""},
    "Iron bracelet": {price: 658.8, level: 0, category: ""},
    "Bacon fondue": {price: 507.6, level: 0, category: ""},
    "Lobster sushi": {price: 637.2, level: 0, category: ""},
    "Buttered popcorn": {price: 126.0, level: 0, category: ""},
    "Fried rice": {price: 205.2, level: 0, category: ""},
    "Corn bread": {price: 72.0, level: 0, category: ""},
    "Potato feta cake": {price: 309.6, level: 0, category: ""},
    "Grilled eggplant": {price: 324.0, level: 0, category: ""},
    "Gingerbread cookie": {price: 273.6, level: 0, category: ""},
    "Fruity milkshake": {price: 759.6, level: 0, category: ""},
    "Casserole": {price: 367.2, level: 0, category: ""},
    "Chocolate pie": {price: 514.8, level: 0, category: ""},
    "BLT salad": {price: 723.6, level: 0, category: ""},
    "Honey": {price: 154.8, level: 0, category: ""},
    "Berry waffles": {price: 604.8, level: 0, category: ""},
    "Potato bread": {price: 284.4, level: 0, category: ""},
    "Raspberry candle": {price: 360.0, level: 0, category: ""},
    "Plum smoothie": {price: 522.0, level: 0, category: ""},
    "Berry juice": {price: 205.2, level: 0, category: ""},
    "Honey face mask": {price: 320.4, level: 0, category: ""},
    "Chicken feed": {price: 7.2, level: 0, category: ""},
    "Caramel apple": {price: 255.6, level: 0, category: ""},
    "Orange tea": {price: 255.6, level: 0, category: ""},
    "Sun hat": {price: 558.0, level: 0, category: ""},
    "Veggie lasagna": {price: 532.8, level: 0, category: ""},
    "Platinum bar": {price: 205.2, level: 0, category: ""},
    "Hand pies": {price: 295.2, level: 0, category: ""},
    "Jelly beans": {price: 684.0, level: 0, category: ""},
    "Big sushi roll": {price: 648.0, level: 0, category: ""},
    "Kimchi": {price: 219.6, level: 0, category: ""},
    "Macaroon": {price: 421.2, level: 0, category: ""},
    "Dried fruit": {price: 266.4, level: 0, category: ""},
    "Iron bar": {price: 129.6, level: 0, category: ""},
    "Cheese": {price: 122.4, level: 0, category: ""},
    "Banana bread": {price: 424.8, level: 0, category: ""},
    "Bread": {price: 21.6, level: 0, category: ""},
    "Birthday bouquet": {price: 349.2, level: 0, category: ""},
    "White sugar": {price: 50.4, level: 0, category: ""},
    "Quesadilla": {price: 241.2, level: 0, category: ""},
    "Cocoa smoothie": {price: 511.2, level: 0, category: ""},
    "Hummus": {price: 277.2, level: 0, category: ""},
    "Sushi roll": {price: 489.6, level: 0, category: ""},
    "Corn dog": {price: 529.2, level: 0, category: ""},
    "Yogurt smoothie": {price: 349.2, level: 0, category: ""},
    "Cucumber smoothie": {price: 266.4, level: 0, category: ""},
    "Mocha milkshake": {price: 856.8, level: 0, category: ""},
    "Pineapple juice": {price: 68.4, level: 0, category: ""},
    "Bright bouquet": {price: 338.4, level: 0, category: ""},
    "Cheese fondue": {price: 493.2, level: 0, category: ""},
    "Grape juice": {price: 104.4, level: 0, category: ""},
    "Pasta salad": {price: 759.6, level: 0, category: ""},
    "Necklace": {price: 727.2, level: 0, category: ""},
    "Broccoli soup": {price: 237.6, level: 0, category: ""},
    "Olive oil": {price: 277.2, level: 0, category: ""},
    "Lemon essential oil": {price: 288.0, level: 0, category: ""},
    "Honey popcorn": {price: 360.0, level: 0, category: ""},
    "Onion melt": {price: 417.6, level: 0, category: ""},
    "Lemon fudge": {price: 590.4, level: 0, category: ""},
    "Asparagus soup": {price: 255.6, level: 0, category: ""},
    "Fancy cake": {price: 450.0, level: 0, category: ""},
    "Broccoli pasta": {price: 345.6, level: 0, category: ""},
    "Noodle soup": {price: 432.0, level: 0, category: ""},
    "Raspberry muffin": {price: 140.4, level: 0, category: ""},
    "Plain donut": {price: 129.6, level: 0, category: ""},
    "Taco": {price: 396.0, level: 0, category: ""},
    "Roasted tomatoes": {price: 118.8, level: 0, category: ""},
    "Rice ball": {price: 464.4, level: 0, category: ""},
    "Affogato": {price: 435.6, level: 0, category: ""},
    "Tofu dog": {price: 367.2, level: 0, category: ""},
    "Veggie bagel": {price: 532.8, level: 0, category: ""},
    "Lemon lotion": {price: 403.2, level: 0, category: ""},
    "Carrot pie": {price: 82.8, level: 0, category: ""},
    "Rice": {price: 18.0, level: 0, category: ""},
    "Goat Milk": {price: 64.8, level: 0, category: ""},
    "Eggplant": {price: 14.4, level: 0, category: ""},
    "Bell Pepper": {price: 36.0, level: 0, category: ""},
    "Cabbage": {price: 18.0, level: 0, category: ""},
    "Ginger": {price: 28.8, level: 0, category: ""},
    "Cherry": {price: 68.4, level: 0, category: ""},
    "Guava": {price: 111.6, level: 0, category: ""},
    "Fish Fillet": {price: 54.0, level: 0, category: ""},
    "Lemon": {price: 93.6, level: 0, category: ""},
    "Bacon": {price: 50.4, level: 0, category: ""},
    "Corn": {price: 7.2, level: 0, category: ""},
    "Soybean": {price: 10.8, level: 0, category: ""},
    "Pumpkin": {price: 32.4, level: 0, category: ""},
    "Sesame": {price: 18.0, level: 0, category: ""},
    "Pomegranate": {price: 111.6, level: 0, category: ""},
    "Honeycomb": {price: 68.4, level: 0, category: ""},
    "Clay": {price: 18.0, level: 0, category: ""},
    "Chili Pepper": {price: 36.0, level: 0, category: ""},
    "Lily": {price: 21.6, level: 0, category: ""},
    "Asparagus": {price: 43.2, level: 0, category: ""},
    "Cacao": {price: 86.4, level: 0, category: ""},
    "Banana": {price: 104.4, level: 0, category: ""},
    "Passion Fruit": {price: 18.0, level: 0, category: ""},
    "Mango": {price: 100.8, level: 0, category: ""},
    "Wool": {price: 54.0, level: 0, category: ""},
    "Watermelon": {price: 39.6, level: 0, category: ""},
    "Blackberry": {price: 82.8, level: 0, category: ""},
    "Garlic": {price: 14.4, level: 0, category: ""},
    "Grapes": {price: 32.4, level: 0, category: ""},
    "Indigo": {price: 25.2, level: 0, category: ""},
    "Plum": {price: 82.8, level: 0, category: ""},
    "Strawberry": {price: 50.4, level: 0, category: ""},
    "Olive": {price: 82.8, level: 0, category: ""},
    "Oats": {price: 7.2, level: 0, category: ""},
    "Tea Leaf": {price: 43.2, level: 0, category: ""},
    "Egg": {price: 18.0, level: 0, category: ""},
    "Peanuts": {price: 234.0, level: 0, category: ""},
    "Cotton": {price: 28.8, level: 0, category: ""},
    "Carrot": {price: 7.2, level: 0, category: ""},
    "Coconut": {price: 108.0, level: 0, category: ""},
    "Lobster Tail": {price: 201.6, level: 0, category: ""},
    "Chickpea": {price: 18.0, level: 0, category: ""},
    "Mushroom": {price: 10.8, level: 0, category: ""},
    "Cucumber": {price: 14.4, level: 0, category: ""},
    "Raspberry": {price: 46.8, level: 0, category: ""},
    "Peony": {price: 36.0, level: 0, category: ""},
    "Wheat": {price: 3.6, level: 0, category: ""},
    "Pineapple": {price: 14.4, level: 0, category: ""},
    "Milk": {price: 32.4, level: 0, category: ""},
    "Duck Feather": {price: 140.4, level: 0, category: ""},
    "Sunflower": {price: 21.6, level: 0, category: ""},
    "Beetroot": {price: 14.4, level: 0, category: ""},
    "Coffee Bean": {price: 64.8, level: 0, category: ""},
    "Mint": {price: 32.4, level: 0, category: ""},
    "Orange": {price: 97.2, level: 0, category: ""},
    "Onion": {price: 39.6, level: 0, category: ""},
    "Apple": {price: 39.6, level: 0, category: ""},
    "Tomato": {price: 43.2, level: 0, category: ""},
    "Sugarcane": {price: 14.4, level: 0, category: ""},
    "Broccoli": {price: 21.6, level: 0, category: ""},
    "Peach": {price: 100.8, level: 0, category: ""},
    "Lettuce": {price: 32.4, level: 0, category: ""},
    "Potato": {price: 36.0, level: 0, category: ""},
    "Axe": {price: 36.0, level: 0, category: ""},
    "Bolt": {price: 270.0, level: 0, category: ""},
    "Brick": {price: 342.0, level: 0, category: ""},
    "Duct Tape": {price: 270.0, level: 0, category: ""},
    "Dynamite": {price: 25.0, level: 0, category: ""},
    "Hammer": {price: 342.0, level: 0, category: ""},
    "Hand Drill": {price: 342.0, level: 0, category: ""},
    "Land Deed": {price: 403.0, level: 0, category: ""},
    "Mallet": {price: 403.0, level: 0, category: ""},
    "Map Piece": {price: 450.0, level: 0, category: ""},
    "Marker Stake": {price: 403.0, level: 0, category: ""},
    "Nail": {price: 270.0, level: 0, category: ""},
    "Paint Bucket": {price: 342.0, level: 0, category: ""},
    "Pickaxe": {price: 126.0, level: 0, category: ""},
    "Plank": {price: 270.0, level: 0, category: ""},
    "Saw": {price: 54.0, level: 0, category: ""},
    "Screw": {price: 270.0, level: 0, category: ""},
    "Shovel": {price: 108.0, level: 0, category: ""},
    "Stone Block": {price: 342.0, level: 0, category: ""},
    "Tar Bucket": {price: 342.0, level: 0, category: ""},
    "TNT Barrel": {price: 72.0, level: 0, category: ""},
    "Wood Panel": {price: 270.0, level: 0, category: ""},
    "Help": {price: 100.0, level: 0, category: ""},
} as { [key: string]: ItemInformation }

export default itemPrices
export type { ItemInformation }