type ItemInformation = {
    price: number;
    level: number;
    categories: string[];
    requiredItems: { [key: string]: number };
}

const itemPrices = {
    "Vanilla ice cream": { 'price': 172.8, 'level': 29, 'categories': ['Ice Cream Maker', 'Milk', 'Cream', 'White Sugar', 'Products'], 'requiredItems': { 'Milk': 1, 'Cream': 1, 'White sugar': 1 } },
    "Top hat": { 'price': 619.2, 'level': 72, 'categories': ['Hat Maker', 'Cotton Fabric', 'Refined Coal', 'Duck Feather', 'Products'], 'requiredItems': { 'Cotton fabric': 3, 'Refined coal': 1, 'Duck Feather': 1 } },
    "Pomegranate cake": { 'price': 316.8, 'level': 108, 'categories': ['Cake Oven', 'Wheat', 'Egg', 'Cream', 'Pomegranate', 'Products'], 'requiredItems': { 'Pomegranate': 1, 'Egg': 2, 'Cream': 2, 'Wheat': 6 } },
    "Strawberry jam": { 'price': 270.0, 'level': 50, 'categories': ['Jam Maker', 'Strawberry', 'Products'], 'requiredItems': { 'Strawberry': 3 } },
    "Cream cake": { 'price': 219.6, 'level': 23, 'categories': ['Cake Oven', 'Wheat', 'Cream', 'White Sugar', 'Products'], 'requiredItems': { 'Wheat': 5, 'Cream': 1, 'White sugar': 1 } },
    "Caffè mocha": { 'price': 291.6, 'level': 45, 'categories': ['Coffee Kiosk', 'Cream', 'Cacao', 'Coffee Bean', 'Products'], 'requiredItems': { 'Coffee Bean': 1, 'Cream': 1, 'Cacao': 2 } },
    "Plain cupcake": { 'price': 280.8, 'level': 109, 'categories': ['Cupcake Maker', 'Milk', 'Egg', 'Wheat', 'White Sugar', 'Products'], 'requiredItems': { 'Milk': 2, 'White sugar': 3, 'Egg': 1, 'Wheat': 5 } },
    "Mango juice": { 'price': 230.4, 'level': 97, 'categories': ['Juice Press', 'Mango', 'Products'], 'requiredItems': { 'Mango': 2 } },
    "Cream": { 'price': 50.4, 'level': 6, 'categories': ['Dairy', 'Milk', 'Products'], 'requiredItems': { 'Milk': 1 } },
    "Sesame brittle": { 'price': 270.0, 'level': 78, 'categories': ['Candy Machine', 'Honey', 'Sesame', 'Ginger', 'Products'], 'requiredItems': { 'Sesame': 3, 'Ginger': 1, 'Honey': 1 } },
    "Egg sushi": { 'price': 550.8, 'level': 63, 'categories': ['Sushi Bar', 'Egg', 'Brown Sugar', 'Soy Sauce', 'Rice', 'Products'], 'requiredItems': { 'Brown sugar': 1, 'Egg': 4, 'Rice': 15, 'Soy sauce': 1 } },
    "Potted plant": { 'price': 151.2, 'level': 96, 'categories': ['Pottery Studio', 'Clay', 'Sunflower', 'Products'], 'requiredItems': { 'Clay': 3, 'Sunflower': 1 } },
    "Pig feed": { 'price': 14.4, 'level': 10, 'categories': ['Feed Mill', 'Soybean', 'Carrot', 'Products'], 'requiredItems': { 'Carrot': 2, 'Soybean': 1 } },
    "Falafel": { 'price': 226.8, 'level': 98, 'categories': ['Deep Fryer', 'Chickpea', 'Onion', 'Garlic', 'Chili Pepper', 'Products'], 'requiredItems': { 'Chickpea': 3, 'Onion': 2, 'Garlic': 2, 'Chili Pepper': 1 } },
    "Spicy pasta": { 'price': 576.0, 'level': 87, 'categories': ['Pasta Kitchen', 'Chili Pepper', 'Onion', 'Fresh Pasta', 'Tomato Sauce', 'Products'], 'requiredItems': { 'Fresh pasta': 3, 'Tomato sauce': 1, 'Chili Pepper': 3, 'Onion': 2 } },
    "Honey soap": { 'price': 327.6, 'level': 84, 'categories': ['Bath Kiosk', 'Goat Milk', 'Cacao', 'Honeycomb', 'Products'], 'requiredItems': { 'Goat Milk': 1, 'Cacao': 2, 'Honeycomb': 1 } },
    "Cabbage soup": { 'price': 270.0, 'level': 65, 'categories': ['Soup Kitchen', 'Cabbage', 'Potato', 'Bacon', 'Carrot', 'Products'], 'requiredItems': { 'Cabbage': 3, 'Bacon': 2, 'Potato': 2, 'Carrot': 2 } },
    "Flower pendant": { 'price': 698.4, 'level': 98, 'categories': ['Jeweler', 'Gold Bar', 'Platinum Bar', 'Peony', 'Products'], 'requiredItems': { 'Peony': 3, 'Platinum bar': 1, 'Gold bar': 2 } },
    "Peanut Noodles": { 'price': 597.6, 'level': 86, 'categories': ['Wok Kitchen', 'Soy Sauce', 'Ginger', 'Rice Noodles', 'Peanuts', 'Products'], 'requiredItems': { 'Ginger': 1, 'Rice noodles': 1, 'Soy sauce': 1, 'Peanuts': 1 } },
    "Silver ore": { 'price': 18.0, 'level': 24, 'categories': ['Mine', 'Products'], 'requiredItems': { 'Dynamite': 2, 'TNT Barrel': 3, 'Shovel': 4, 'Pickaxe': 5 } },
    "Honey peanuts": { 'price': 468.0, 'level': 63, 'categories': ['Candy Machine', 'Honey', 'Peanuts', 'Products'], 'requiredItems': { 'Honey': 1, 'Peanuts': 1 } },
    "Veggie Platter": { 'price': 266.4, 'level': 74, 'categories': ['Salad Bar', 'Cream', 'Carrot', 'Tomato', 'Bell Pepper', 'Products'], 'requiredItems': { 'Bell Pepper': 2, 'Carrot': 2, 'Tomato': 2, 'Cream': 1 } },
    "Cotton shirt": { 'price': 241.2, 'level': 19, 'categories': ['Sewing Machine', 'Cotton Fabric', 'Products'], 'requiredItems': { 'Cotton fabric': 2 } },
    "Mayonnaise": { 'price': 367.2, 'level': 62, 'categories': ['Sauce Maker', 'Egg', 'Olive Oil', 'Products'], 'requiredItems': { 'Egg': 4, 'Olive oil': 1 } },
    "Orange salad": { 'price': 558.0, 'level': 117, 'categories': ['Salad Bar', 'Orange', 'Cheese', 'Lettuce', 'Pomegranate', 'Products'], 'requiredItems': { 'Cheese': 1, 'Lettuce': 3, 'Pomegranate': 1, 'Orange': 2 } },
    "Fish burger": { 'price': 226.8, 'level': 27, 'categories': ['BBQ Grill', 'Bread', 'Chili Pepper', 'Fish Fillet', 'Products'], 'requiredItems': { 'Fish Fillet': 2, 'Chili Pepper': 1, 'Bread': 2 } },
    "Fish taco": { 'price': 392.4, 'level': 79, 'categories': ['Taco Kitchen', 'Corn Bread', 'Chili Pepper', 'Fish Fillet', 'Lemon', 'Products'], 'requiredItems': { 'Chili Pepper': 2, 'Corn bread': 2, 'Fish Fillet': 1, 'Lemon': 1 } },
    "Peanut Butter and Jelly Sandwich": { 'price': 601.2, 'level': 71, 'categories': ['Sandwich Bar', 'Bread', 'Raspberry Jam', 'Peanuts', 'Products'], 'requiredItems': { 'Bread': 2, 'Raspberry jam': 1, 'Peanuts': 1 } },
    "Breakfast bowl": { 'price': 604.8, 'level': 119, 'categories': ['Yogurt Maker', 'Plain Yogurt', 'Oats', 'Honey', 'Blackberry', 'Products'], 'requiredItems': { 'Plain yogurt': 1, 'Oats': 4, 'Honey': 1, 'Blackberry': 2 } },
    "Tomato juice": { 'price': 162.0, 'level': 31, 'categories': ['Juice Press', 'Tomato', 'Products'], 'requiredItems': { 'Tomato': 3 } },
    "Peach jam": { 'price': 464.4, 'level': 79, 'categories': ['Jam Maker', 'Peach', 'Products'], 'requiredItems': { 'Peach': 3 } },
    "Iced tea": { 'price': 252.0, 'level': 92, 'categories': ['Tea Stand', 'Peach', 'Tea Leaf', 'Products'], 'requiredItems': { 'Peach': 1, 'Tea Leaf': 3 } },
    "Bacon and eggs": { 'price': 201.6, 'level': 11, 'categories': ['BBQ Grill', 'Egg', 'Bacon', 'Products'], 'requiredItems': { 'Egg': 4, 'Bacon': 2 } },
    "Pickles": { 'price': 270.0, 'level': 91, 'categories': ['Preservation Station', 'Cucumber', 'Onion', 'Lemon', 'Products'], 'requiredItems': { 'Cucumber': 3, 'Onion': 2, 'Lemon': 1 } },
    "Feta pie": { 'price': 223.2, 'level': 34, 'categories': ['Pie Oven', 'Wheat', 'Egg', 'Goat Cheese', 'Products'], 'requiredItems': { 'Goat cheese': 1, 'Wheat': 2, 'Egg': 1 } },
    "Hummus wrap": { 'price': 374.4, 'level': 109, 'categories': ['Sandwich Bar', 'Bread', 'Lettuce', 'Hummus', 'Products'], 'requiredItems': { 'Hummus': 1, 'Bread': 1, 'Lettuce': 1 } },
    "Spicy pizza": { 'price': 226.8, 'level': 37, 'categories': ['Bakery', 'Wheat', 'Cheese', 'Chili Pepper', 'Tomato', 'Products'], 'requiredItems': { 'Wheat': 2, 'Tomato': 1, 'Cheese': 1, 'Chili Pepper': 1 } },
    "Cherry juice": { 'price': 216.0, 'level': 30, 'categories': ['Juice Press', 'Cherry', 'Products'], 'requiredItems': { 'Cherry': 2 } },
    "Chocolate roll": { 'price': 604.8, 'level': 95, 'categories': ['Cake Oven', 'Cacao', 'Cream', 'Wheat', 'Mint', 'Products'], 'requiredItems': { 'Cacao': 5, 'Cream': 1, 'Wheat': 3, 'Mint': 3 } },
    "Orange juice": { 'price': 234.0, 'level': 71, 'categories': ['Juice Press', 'Orange', 'Products'], 'requiredItems': { 'Orange': 2 } },
    "Red berry cake": { 'price': 255.6, 'level': 23, 'categories': ['Cake Oven', 'Milk', 'Raspberry', 'Cherry', 'Egg', 'Products'], 'requiredItems': { 'Raspberry': 1, 'Cherry': 2, 'Milk': 1, 'Egg': 1 } },
    "Chocolate popcorn": { 'price': 248.4, 'level': 44, 'categories': ['Popcorn Pot', 'Corn', 'Cacao', 'Products'], 'requiredItems': { 'Corn': 2, 'Cacao': 2 } },
    "Marmalade": { 'price': 457.2, 'level': 74, 'categories': ['Jam Maker', 'Orange', 'Products'], 'requiredItems': { 'Orange': 3 } },
    "Hot dog": { 'price': 370.8, 'level': 75, 'categories': ['Hot Dog Stand', 'Bread', 'Bacon', 'Tomato Sauce', 'Products'], 'requiredItems': { 'Bacon': 2, 'Bread': 1, 'Tomato sauce': 1 } },
    "Peanut Butter Milkshake": { 'price': 619.2, 'level': 68, 'categories': ['Ice Cream Maker', 'Peanuts', 'Milk', 'Cream', 'Cacao', 'Products'], 'requiredItems': { 'Peanuts': 1, 'Milk': 1, 'Cream': 1, 'Cacao': 3 } },
    "Pineapple cake": { 'price': 259.2, 'level': 65, 'categories': ['Cake Oven', 'Wheat', 'Egg', 'Cherry', 'Pineapple', 'Products'], 'requiredItems': { 'Pineapple': 3, 'Egg': 2, 'Cherry': 2, 'Wheat': 4 } },
    "Cotton candy": { 'price': 226.8, 'level': 75, 'categories': ['Candy Machine', 'White Sugar', 'Strawberry', 'Products'], 'requiredItems': { 'White sugar': 1 } },
    "Green smoothie": { 'price': 320.4, 'level': 66, 'categories': ['Smoothie Mixer', 'Apple', 'Lettuce', 'Lemon', 'Products'], 'requiredItems': { 'Lettuce': 5, 'Lemon': 1, 'Apple': 1 } },
    "Vanilla milkshake": { 'price': 673.2, 'level': 124, 'categories': ['New', 'Milkshake Bar', 'Vanilla Ice Cream', 'Cookie', 'Toffee', 'Syrup', 'Products'], 'requiredItems': { 'Vanilla ice cream': 1, 'Cookie': 2, 'Toffee': 1, 'Syrup': 1 } },
    "Mushroom soup": { 'price': 176.4, 'level': 104, 'categories': ['Soup Kitchen', 'Milk', 'Mushroom', 'Onion', 'Products'], 'requiredItems': { 'Mushroom': 3, 'Milk': 1, 'Onion': 2 } },
    "Coal": { 'price': 10.8, 'level': 33, 'categories': ['Mine', 'Products'], 'requiredItems': { 'Dynamite': 2, 'TNT Barrel': 3, 'Shovel': 4, 'Pickaxe': 5 } },
    "Espresso": { 'price': 248.4, 'level': 42, 'categories': ['Coffee Kiosk', 'White Sugar', 'Coffee Bean', 'Products'], 'requiredItems': { 'Coffee Bean': 3, 'White sugar': 1 } },
    "Fish pie": { 'price': 226.8, 'level': 28, 'categories': ['Pie Oven', 'Wheat', 'Egg', 'Fish Fillet', 'Products'], 'requiredItems': { 'Fish Fillet': 3, 'Wheat': 2, 'Egg': 1 } },
    "Tropical smoothie": { 'price': 475.2, 'level': 104, 'categories': ['Smoothie Mixer', 'Coconut', 'Banana', 'Passion Fruit', 'Mango', 'Products'], 'requiredItems': { 'Coconut': 1, 'Banana': 1, 'Passion Fruit': 2, 'Mango': 2 } },
    "Grilled onion": { 'price': 190.8, 'level': 68, 'categories': ['BBQ Grill', 'Butter', 'Onion', 'Products'], 'requiredItems': { 'Butter': 1, 'Onion': 2 } },
    "Cheese omelet": { 'price': 464.4, 'level': 79, 'categories': ['Omelet Station', 'Egg', 'Cheese', 'Tomato', 'Onion', 'Products'], 'requiredItems': { 'Egg': 3, 'Cheese': 2, 'Tomato': 2, 'Onion': 1 } },
    "Rice Omelet": { 'price': 572.4, 'level': 83, 'categories': ['New', 'Omelet Station', 'Egg', 'Tomato Sauce', 'Rice', 'Products'], 'requiredItems': { 'Egg': 3, 'Rice': 1, 'Tomato sauce': 2 } },
    "Egg sandwich": { 'price': 583.2, 'level': 66, 'categories': ['Sandwich Bar', 'Egg', 'Bread', 'Lettuce', 'Mayonnaise', 'Products'], 'requiredItems': { 'Bread': 2, 'Egg': 2, 'Lettuce': 3, 'Mayonnaise': 1 } },
    "Gnocchi": { 'price': 475.2, 'level': 72, 'categories': ['Pasta Kitchen', 'Wheat', 'Butter', 'Tomato', 'Potato', 'Products'], 'requiredItems': { 'Potato': 4, 'Tomato': 3, 'Wheat': 2, 'Butter': 2 } },
    "Pineapple coconut bars": { 'price': 284.4, 'level': 120, 'categories': ['Bakery', 'Oats', 'Pineapple', 'White Sugar', 'Coconut', 'Products'], 'requiredItems': { 'Coconut': 1, 'White sugar': 2, 'Oats': 3, 'Pineapple': 2 } },
    "Hamburger": { 'price': 180.0, 'level': 18, 'categories': ['BBQ Grill', 'Bread', 'Bacon', 'Products'], 'requiredItems': { 'Bread': 2, 'Bacon': 2 } },
    "Shepherds pie": { 'price': 280.8, 'level': 39, 'categories': ['Pie Oven', 'Carrot', 'Bacon', 'Pumpkin', 'Potato', 'Products'], 'requiredItems': { 'Potato': 2, 'Bacon': 2, 'Carrot': 2, 'Pumpkin': 2 } },
    "Peach ice cream": { 'price': 450.0, 'level': 83, 'categories': ['Ice Cream Maker', 'Cream', 'Honey', 'Peach', 'Products'], 'requiredItems': { 'Cream': 1, 'Honey': 1, 'Peach': 2 } },
    "Coleslaw": { 'price': 468.0, 'level': 75, 'categories': ['Salad Bar', 'Cabbage', 'Carrot', 'Mayonnaise', 'Products'], 'requiredItems': { 'Cabbage': 3, 'Carrot': 2, 'Mayonnaise': 1 } },
    "Lollipop": { 'price': 342.0, 'level': 57, 'categories': ['Candy Machine', 'Syrup', 'Cherry', 'Strawberry', 'Products'], 'requiredItems': { 'Syrup': 1, 'Cherry': 1, 'Strawberry': 2 } },
    "Salsa": { 'price': 252.0, 'level': 77, 'categories': ['Sauce Maker', 'Chili Pepper', 'Tomato', 'Onion', 'Products'], 'requiredItems': { 'Chili Pepper': 2, 'Onion': 2, 'Tomato': 2 } },
    "Hot chocolate": { 'price': 316.8, 'level': 47, 'categories': ['Coffee Kiosk', 'Milk', 'Cream', 'White Sugar', 'Cacao', 'Products'], 'requiredItems': { 'Cacao': 2, 'Cream': 1, 'Milk': 1, 'White sugar': 1 } },
    "Goat cheese toast": { 'price': 302.4, 'level': 92, 'categories': ['Sandwich Bar', 'Bread', 'Grapes', 'Goat Cheese', 'Products'], 'requiredItems': { 'Grapes': 3, 'Goat cheese': 1, 'Bread': 1 } },
    "Winter veggies": { 'price': 198.0, 'level': 72, 'categories': ['BBQ Grill', 'Carrot', 'Pumpkin', 'Potato', 'Beetroot', 'Products'], 'requiredItems': { 'Beetroot': 2, 'Carrot': 2, 'Potato': 2, 'Pumpkin': 2 } },
    "Watermelon juice": { 'price': 108.0, 'level': 92, 'categories': ['Juice Press', 'Watermelon', 'Products'], 'requiredItems': { 'Watermelon': 2 } },
    "Goat feed": { 'price': 14.4, 'level': 32, 'categories': ['Feed Mill', 'Wheat', 'Corn', 'Carrot', 'Products'], 'requiredItems': { 'Wheat': 1, 'Corn': 1, 'Carrot': 2 } },
    "Stuffed peppers": { 'price': 352.8, 'level': 80, 'categories': ['BBQ Grill', 'Bell Pepper', 'Bacon', 'Rice', 'Cheese', 'Products'], 'requiredItems': { 'Bell Pepper': 1, 'Rice': 3, 'Cheese': 1 } },
    "Spring omelet": { 'price': 230.4, 'level': 77, 'categories': ['Omelet Station', 'Egg', 'Butter', 'Asparagus', 'Products'], 'requiredItems': { 'Egg': 2, 'Asparagus': 2, 'Butter': 1 } },
    "Flower crown": { 'price': 331.2, 'level': 86, 'categories': ['Hat Maker', 'Cotton', 'Peony', 'Products'], 'requiredItems': { 'Peony': 5, 'Cotton': 4 } },
    "Cookie cupcake": { 'price': 712.8, 'level': 114, 'categories': ['Cupcake Maker', 'Plain Cupcake', 'Cream', 'Cookie', 'Cacao', 'Products'], 'requiredItems': { 'Plain cupcake': 1, 'Cream': 2, 'Cookie': 2, 'Cacao': 1 } },
    "Passion fruit pie": { 'price': 111.6, 'level': 92, 'categories': ['Pie Oven', 'Wheat', 'Egg', 'Passion Fruit', 'Products'], 'requiredItems': { 'Passion Fruit': 3, 'Wheat': 2, 'Egg': 1 } },
    "Flower shawl": { 'price': 295.2, 'level': 71, 'categories': ['Loom', 'Wool', 'Blackberry', 'Sunflower', 'Products'], 'requiredItems': { 'Wool': 2, 'Sunflower': 3, 'Blackberry': 1 } },
    "Spicy fish": { 'price': 543.6, 'level': 79, 'categories': ['Wok Kitchen', 'Chili Pepper', 'Fish Fillet', 'Olive Oil', 'Garlic', 'Products'], 'requiredItems': { 'Fish Fillet': 1, 'Chili Pepper': 3, 'Garlic': 5, 'Olive oil': 1 } },
    "Apple pie": { 'price': 270.0, 'level': 28, 'categories': ['Pie Oven', 'Wheat', 'Egg', 'Apple', 'Syrup', 'Products'], 'requiredItems': { 'Apple': 3, 'Wheat': 2, 'Egg': 1, 'Syrup': 1 } },
    "Honey apple cake": { 'price': 482.4, 'level': 42, 'categories': ['Cake Oven', 'Wheat', 'Egg', 'Apple', 'Honey', 'Products'], 'requiredItems': { 'Wheat': 2, 'Egg': 2, 'Apple': 2, 'Honey': 2 } },
    "Lobster soup": { 'price': 612.0, 'level': 46, 'categories': ['Soup Kitchen', 'Cream', 'Chili Pepper', 'Tomato', 'Lobster Tail', 'Products'], 'requiredItems': { 'Lobster Tail': 2, 'Tomato': 1, 'Chili Pepper': 2, 'Cream': 1 } },
    "Caffè latte": { 'price': 219.6, 'level': 43, 'categories': ['Coffee Kiosk', 'Milk', 'White Sugar', 'Coffee Bean', 'Products'], 'requiredItems': { 'Coffee Bean': 2, 'White sugar': 1, 'Milk': 1 } },
    "Violet dress": { 'price': 327.6, 'level': 25, 'categories': ['Sewing Machine', 'Indigo', 'Cotton Fabric', 'Raspberry', 'Products'], 'requiredItems': { 'Cotton fabric': 2, 'Raspberry': 1, 'Indigo': 1 } },
    "Diamond ring": { 'price': 824.4, 'level': 40, 'categories': ['Jeweler', 'Gold Bar', 'Platinum Bar', 'Diamond', 'Products'], 'requiredItems': { 'Gold bar': 2, 'Platinum bar': 2, 'Diamond': 1 } },
    "Bacon Fries": { 'price': 302.4, 'level': 87, 'categories': ['Deep Fryer', 'Chili Pepper', 'Bacon', 'Potato', 'Garlic', 'Products'], 'requiredItems': { 'Chili Pepper': 1, 'Bacon': 2, 'Potato': 4, 'Garlic': 1 } },
    "Guava juice": { 'price': 252.0, 'level': 104, 'categories': ['Juice Press', 'Guava', 'Products'], 'requiredItems': { 'Guava': 2 } },
    "Sweet porridge": { 'price': 460.8, 'level': 120, 'categories': ['Porridge Bar', 'Peach', 'Honey', 'Oats', 'Products'], 'requiredItems': { 'Peach': 1, 'Honey': 2, 'Oats': 3 } },
    "Fruit salad": { 'price': 597.6, 'level': 82, 'categories': ['Salad Bar', 'Blackberry', 'Strawberry', 'Honey', 'Orange', 'Products'], 'requiredItems': { 'Blackberry': 2, 'Honey': 1, 'Orange': 1, 'Strawberry': 3 } },
    "Lobster skewer": { 'price': 417.6, 'level': 48, 'categories': ['BBQ Grill', 'Chili Pepper', 'Honey', 'Lobster Tail', 'Products'], 'requiredItems': { 'Lobster Tail': 1, 'Chili Pepper': 1, 'Honey': 1 } },
    "Bacon toast": { 'price': 648.0, 'level': 65, 'categories': ['Sandwich Bar', 'Bread', 'Bacon', 'Lettuce', 'Mayonnaise', 'Products'], 'requiredItems': { 'Bacon': 2, 'Bread': 2, 'Lettuce': 3, 'Mayonnaise': 1 } },
    "Asparagus quiche": { 'price': 302.4, 'level': 49, 'categories': ['Pie Oven', 'Egg', 'Bacon', 'Cheese', 'Asparagus', 'Products'], 'requiredItems': { 'Asparagus': 2, 'Egg': 2, 'Cheese': 1, 'Wheat': 4 } },
    "Honey toast": { 'price': 255.6, 'level': 69, 'categories': ['Sandwich Bar', 'Egg', 'Bread', 'Milk', 'Honey', 'Products'], 'requiredItems': { 'Bread': 1, 'Egg': 1, 'Milk': 1, 'Honey': 1 } },
    "Baked potato": { 'price': 298.8, 'level': 35, 'categories': ['BBQ Grill', 'Cream', 'Cheese', 'Chili Pepper', 'Potato', 'Products'], 'requiredItems': { 'Potato': 2, 'Chili Pepper': 1, 'Cream': 1, 'Cheese': 1 } },
    "Carrot cake": { 'price': 165.6, 'level': 21, 'categories': ['Cake Oven', 'Brown Sugar', 'Carrot', 'Butter', 'Products'], 'requiredItems': { 'Carrot': 2, 'Butter': 1, 'Brown sugar': 1 } },
    "Cherry popsicle": { 'price': 352.8, 'level': 33, 'categories': ['Ice Cream Maker', 'Syrup', 'Cherry Juice', 'Products'], 'requiredItems': { 'Syrup': 1, 'Cherry juice': 1 } },
    "Red scarf": { 'price': 288.0, 'level': 48, 'categories': ['Loom', 'Wool', 'Strawberry', 'Products'], 'requiredItems': { 'Wool': 2, 'Strawberry': 2 } },
    "Guava compote": { 'price': 421.2, 'level': 104, 'categories': ['Preservation Station', 'Guava', 'Lemon', 'White Sugar', 'Products'], 'requiredItems': { 'Guava': 2, 'Lemon': 1, 'White sugar': 1 } },
    "Pizza": { 'price': 190.8, 'level': 33, 'categories': ['Bakery', 'Wheat', 'Cheese', 'Tomato', 'Products'], 'requiredItems': { 'Wheat': 2, 'Tomato': 1, 'Cheese': 1 } },
    "Tofu stir fry": { 'price': 306.0, 'level': 89, 'categories': ['Wok Kitchen', 'Soybean', 'Sesame', 'Onion', 'Broccoli', 'Products'], 'requiredItems': { 'Soybean': 3, 'Onion': 3, 'Broccoli': 3, 'Sesame': 3 } },
    "Tomato soup": { 'price': 478.8, 'level': 47, 'categories': ['Soup Kitchen', 'Chili Pepper', 'Tomato', 'Tomato Juice', 'Goat Cheese', 'Products'], 'requiredItems': { 'Tomato': 2, 'Tomato juice': 1, 'Chili Pepper': 1, 'Goat cheese': 1 } },
    "Samosa": { 'price': 223.2, 'level': 103, 'categories': ['Deep Fryer', 'Chickpea', 'Wheat', 'Potato', 'Chili Pepper', 'Products'], 'requiredItems': { 'Chickpea': 2, 'Wheat': 4, 'Potato': 3, 'Chili Pepper': 1 } },
    "Raspberry mocha": { 'price': 259.2, 'level': 46, 'categories': ['Coffee Kiosk', 'Cream', 'Raspberry', 'Cacao', 'Coffee Bean', 'Products'], 'requiredItems': { 'Coffee Bean': 1, 'Cream': 1, 'Cacao': 1, 'Raspberry': 1 } },
    "Plain waffles": { 'price': 198.0, 'level': 114, 'categories': ['Waffle Maker', 'Egg', 'Wheat', 'White Sugar', 'Products'], 'requiredItems': { 'White sugar': 2, 'Egg': 3, 'Wheat': 5 } },
    "Lemon cake": { 'price': 896.4, 'level': 68, 'categories': ['Cake Oven', 'Wheat', 'Egg', 'Cream', 'Lemon Curd', 'Products'], 'requiredItems': { 'Lemon curd': 2, 'Egg': 2, 'Cream': 1, 'Wheat': 3 } },
    "Honey tea": { 'price': 313.2, 'level': 83, 'categories': ['Tea Stand', 'Honey', 'Tea Leaf', 'Products'], 'requiredItems': { 'Honey': 1, 'Tea Leaf': 3 } },
    "Popcorn": { 'price': 32.4, 'level': 8, 'categories': ['Popcorn Pot', 'Corn', 'Products'], 'requiredItems': { 'Corn': 2 } },
    "Tea pot": { 'price': 219.6, 'level': 94, 'categories': ['Pottery Studio', 'Clay', 'Coffee Bean', 'Gold Ore', 'Products'], 'requiredItems': { 'Clay': 3, 'Coffee Bean': 1, 'Gold ore': 1 } },
    "Blanket": { 'price': 1098.0, 'level': 59, 'categories': ['Sewing Machine', 'Pumpkin', 'Cotton Fabric', 'Duck Feather', 'Products'], 'requiredItems': { 'Cotton fabric': 3, 'Pumpkin': 1, 'Duck Feather': 5 } },
    "Chickpea stew": { 'price': 284.4, 'level': 106, 'categories': ['Stew Pot', 'Coconut', 'Tomato', 'Chickpea', 'Products'], 'requiredItems': { 'Coconut': 1, 'Tomato': 2, 'Chickpea': 3 } },
    "Apple porridge": { 'price': 522.0, 'level': 119, 'categories': ['Porridge Bar', 'Apple', 'Apple Jam', 'Oats', 'Products'], 'requiredItems': { 'Apple': 1, 'Apple jam': 2, 'Oats': 4 } },
    "Chocolate waffles": { 'price': 637.2, 'level': 117, 'categories': ['Waffle Maker', 'Plain Waffles', 'Cacao', 'Strawberry', 'Banana', 'Products'], 'requiredItems': { 'Plain waffles': 1, 'Cacao': 2, 'Strawberry': 3, 'Banana': 1 } },
    "Strawberry cake": { 'price': 316.8, 'level': 35, 'categories': ['Cake Oven', 'Wheat', 'Cream', 'White Sugar', 'Strawberry', 'Products'], 'requiredItems': { 'Wheat': 3, 'Strawberry': 2, 'Cream': 1, 'White sugar': 1 } },
    "Cookie": { 'price': 104.4, 'level': 10, 'categories': ['Bakery', 'Wheat', 'Egg', 'Brown Sugar', 'Products'], 'requiredItems': { 'Wheat': 2, 'Egg': 2, 'Brown sugar': 1 } },
    "Sheep feed": { 'price': 14.4, 'level': 16, 'categories': ['Feed Mill', 'Wheat', 'Soybean', 'Products'], 'requiredItems': { 'Wheat': 3, 'Soybean': 1 } },
    "Fish and chips": { 'price': 244.8, 'level': 41, 'categories': ['BBQ Grill', 'Fish Fillet', 'Potato', 'Products'], 'requiredItems': { 'Fish Fillet': 2, 'Potato': 3 } },
    "Colourful omelet": { 'price': 136.8, 'level': 77, 'categories': ['Note', 'Omelet Station', 'Egg', 'Carrot', 'Bell Pepper', 'Cabbage', 'Products'], 'requiredItems': { 'Egg': 2, 'Carrot': 2, 'Bell Pepper': 1, 'Cabbage': 1 } },
    "Plain yogurt": { 'price': 234.0, 'level': 103, 'categories': ['Yogurt Maker', 'Milk', 'Cream', 'Products'], 'requiredItems': { 'Milk': 3, 'Cream': 2 } },
    "Grape jam": { 'price': 162.0, 'level': 85, 'categories': ['Jam Maker', 'Grapes', 'Products'], 'requiredItems': { 'Grapes': 3 } },
    "Strawberry yogurt": { 'price': 529.2, 'level': 105, 'categories': ['Yogurt Maker', 'Plain Yogurt', 'Strawberry Jam', 'Products'], 'requiredItems': { 'Plain yogurt': 1, 'Strawberry jam': 1 } },
    "Apple Ginger Tea": { 'price': 169.2, 'level': 88, 'categories': ['Tea Stand', 'Apple', 'Ginger', 'Tea Leaf', 'Products'], 'requiredItems': { 'Ginger': 1, 'Apple': 2, 'Tea Leaf': 1 } },
    "Toffee": { 'price': 176.4, 'level': 52, 'categories': ['Candy Machine', 'Wheat', 'Butter', 'White Sugar', 'Products'], 'requiredItems': { 'Butter': 1, 'Wheat': 1, 'White sugar': 1 } },
    "Mushroom pot pie": { 'price': 162.0, 'level': 97, 'categories': ['Pie Oven', 'Cabbage', 'Mushroom', 'Wheat', 'Egg', 'Products'], 'requiredItems': { 'Mushroom': 3, 'Cabbage': 3, 'Wheat': 3, 'Egg': 2 } },
    "Rice noodles": { 'price': 100.8, 'level': 73, 'categories': ['Pasta Maker', 'Rice', 'Products'], 'requiredItems': { 'Rice': 5 } },
    "Candy bouquet": { 'price': 554.4, 'level': 90, 'categories': ['Flower Shop', 'Caramel Apple', 'Toffee', 'Peony', 'Products'], 'requiredItems': { 'Peony': 3, 'Caramel apple': 1, 'Toffee': 1 } },
    "Mint tea": { 'price': 255.6, 'level': 97, 'categories': ['Tea Stand', 'Tea Leaf', 'Watermelon', 'Mint', 'Products'], 'requiredItems': { 'Tea Leaf': 3, 'Watermelon': 1, 'Mint': 1 } },
    "Wheat Bundle": { 'price': 50.4, 'level': 0, 'categories': [], 'requiredItems': { 'Wheat': 75 } },
    "Pumpkin soup": { 'price': 392.4, 'level': 49, 'categories': ['Soup Kitchen', 'Carrot', 'Butter', 'Pumpkin', 'Honey', 'Products'], 'requiredItems': { 'Pumpkin': 3, 'Butter': 1, 'Honey': 1, 'Carrot': 2 } },
    "Chili popcorn": { 'price': 122.4, 'level': 25, 'categories': ['Popcorn Pot', 'Corn', 'Chili Pepper', 'Products'], 'requiredItems': { 'Corn': 2, 'Chili Pepper': 2 } },
    "Mixed smoothie": { 'price': 504.0, 'level': 88, 'categories': ['Smoothie Mixer', 'Lemon', 'Orange', 'Peach', 'Products'], 'requiredItems': { 'Lemon': 1, 'Orange': 2, 'Peach': 2 } },
    "Bell Pepper Soup": { 'price': 439.2, 'level': 81, 'categories': ['Soup Kitchen', 'Bread', 'Chili Pepper', 'Olive Oil', 'Bell Pepper', 'Products'], 'requiredItems': { 'Bread': 1, 'Olive oil': 1, 'Chili Pepper': 1, 'Bell Pepper': 2 } },
    "Pomegranate tea": { 'price': 313.2, 'level': 107, 'categories': ['Tea Stand', 'Pomegranate', 'Tea Leaf', 'Products'], 'requiredItems': { 'Pomegranate': 1, 'Tea Leaf': 4 } },
    "Summer rolls": { 'price': 316.8, 'level': 78, 'categories': ['Salad Bar', 'Carrot', 'Chili Pepper', 'Lettuce', 'Rice Noodles', 'Products'], 'requiredItems': { 'Rice noodles': 2, 'Carrot': 2, 'Lettuce': 1, 'Chili Pepper': 1 } },
    "Exfoliating soap": { 'price': 363.6, 'level': 93, 'categories': ['Bath Kiosk', 'Coffee Bean', 'Cacao', 'Raspberry', 'Products'], 'requiredItems': { 'Cacao': 2, 'Coffee Bean': 2, 'Raspberry': 1 } },
    "Cheesecake": { 'price': 284.4, 'level': 24, 'categories': ['Cake Oven', 'Cookie', 'Cheese', 'Products'], 'requiredItems': { 'Cheese': 1, 'Cookie': 1 } },
    "Cloche hat": { 'price': 468.0, 'level': 70, 'categories': ['Hat Maker', 'Wool', 'Strawberry', 'Products'], 'requiredItems': { 'Strawberry': 2, 'Wool': 6 } },
    "Passion fruit jam": { 'price': 118.8, 'level': 96, 'categories': ['Jam Maker', 'Passion Fruit', 'Products'], 'requiredItems': { 'Passion Fruit': 3 } },
    "Fruit cake": { 'price': 450.0, 'level': 89, 'categories': ['Cake Oven', 'Wheat', 'Cherry', 'Orange', 'Grapes', 'Products'], 'requiredItems': { 'Grapes': 2, 'Orange': 2, 'Cherry': 2, 'Wheat': 3 } },
    "Cucumber sandwich": { 'price': 464.4, 'level': 79, 'categories': ['Sandwich Bar', 'Bread', 'Cucumber', 'Mayonnaise', 'Products'], 'requiredItems': { 'Cucumber': 2, 'Mayonnaise': 1, 'Bread': 2 } },
    "Banana split": { 'price': 403.2, 'level': 96, 'categories': ['Ice Cream Maker', 'Cream', 'Cherry', 'Banana', 'Products'], 'requiredItems': { 'Banana': 1, 'Cream': 1, 'Cherry': 3 } },
    "Iced banana latte": { 'price': 277.2, 'level': 88, 'categories': ['Coffee Kiosk', 'Milk', 'Coffee Bean', 'Banana', 'Products'], 'requiredItems': { 'Banana': 1, 'Coffee Bean': 2, 'Milk': 1 } },
    "Onion soup": { 'price': 327.6, 'level': 72, 'categories': ['Soup Kitchen', 'Cheese', 'Onion', 'Bread', 'Products'], 'requiredItems': { 'Bread': 2, 'Cheese': 1, 'Onion': 3 } },
    "Passion fruit juice": { 'price': 64.8, 'level': 88, 'categories': ['Juice Press', 'Passion Fruit', 'Products'], 'requiredItems': { 'Passion Fruit': 2 } },
    "Snack mix": { 'price': 309.6, 'level': 64, 'categories': ['Popcorn Pot', 'Corn', 'Sesame', 'Peanuts', 'Products'], 'requiredItems': { 'Corn': 2, 'Sesame': 1, 'Peanuts': 1 } },
    "Clay mug": { 'price': 212.4, 'level': 99, 'categories': ['Pottery Studio', 'Clay', 'Indigo', 'Peony', 'Products'], 'requiredItems': { 'Clay': 3, 'Indigo': 2, 'Peony': 1 } },
    "Summer salad": { 'price': 554.4, 'level': 84, 'categories': ['Salad Bar', 'Tomato', 'Peach', 'Onion', 'Goat Cheese', 'Products'], 'requiredItems': { 'Goat cheese': 1, 'Onion': 3, 'Peach': 1, 'Tomato': 3 } },
    "Soy sauce": { 'price': 154.8, 'level': 54, 'categories': ['Sauce Maker', 'Wheat', 'Soybean', 'Products'], 'requiredItems': { 'Soybean': 9, 'Wheat': 1 } },
    "Fish skewer": { 'price': 176.4, 'level': 96, 'categories': ['BBQ Grill', 'Fish Fillet', 'Sesame', 'Mushroom', 'Ginger', 'Products'], 'requiredItems': { 'Fish Fillet': 1, 'Mushroom': 3, 'Ginger': 1, 'Sesame': 2 } },
    "Tart dressing": { 'price': 288.0, 'level': 100, 'categories': ['Sauce Maker', 'Passion Fruit', 'Chili Pepper', 'Honey', 'Products'], 'requiredItems': { 'Passion Fruit': 2, 'Chili Pepper': 2, 'Honey': 1 } },
    "Lemon tea": { 'price': 241.2, 'level': 86, 'categories': ['Tea Stand', 'Lemon', 'Tea Leaf', 'Products'], 'requiredItems': { 'Lemon': 1, 'Tea Leaf': 3 } },
    "Fried candy bar": { 'price': 658.8, 'level': 100, 'categories': ['Deep Fryer', 'Cacao', 'Cookie', 'Peanuts', 'Products'], 'requiredItems': { 'Cacao': 3, 'Cookie': 1, 'Peanuts': 1 } },
    "Chili stew": { 'price': 370.8, 'level': 109, 'categories': ['Stew Pot', 'Chili Pepper', 'Bacon', 'Onion', 'Cream', 'Products'], 'requiredItems': { 'Chili Pepper': 3, 'Bacon': 2, 'Onion': 2, 'Cream': 1 } },
    "Strawberry candle": { 'price': 370.8, 'level': 48, 'categories': ['Candle Maker', 'Strawberry', 'Beeswax', 'Products'], 'requiredItems': { 'Beeswax': 1, 'Strawberry': 2 } },
    "Fresh porridge": { 'price': 435.6, 'level': 122, 'categories': ['Porridge Bar', 'Pomegranate', 'Mint', 'Coconut', 'Oats', 'Products'], 'requiredItems': { 'Pomegranate': 1, 'Mint': 2, 'Coconut': 2, 'Oats': 3 } },
    "Gold bar": { 'price': 180.0, 'level': 25, 'categories': ['Smelters', 'Gold Ore', 'Products'], 'requiredItems': { 'Gold ore': 3 } },
    "Tropical cupcake": { 'price': 572.4, 'level': 112, 'categories': ['Cupcake Maker', 'Plain Cupcake', 'Pineapple', 'Coconut', 'Products'], 'requiredItems': { 'Plain cupcake': 1, 'Pineapple': 3, 'Coconut': 2 } },
    "Veggie bouquet": { 'price': 352.8, 'level': 106, 'categories': ['Flower Shop', 'Broccoli', 'Tomato', 'Mushroom', 'Cotton Fabric', 'Products'], 'requiredItems': { 'Broccoli': 3, 'Tomato': 3, 'Mushroom': 3, 'Cotton fabric': 1 } },
    "Tropical yogurt": { 'price': 457.2, 'level': 109, 'categories': ['Yogurt Maker', 'Plain Yogurt', 'Raspberry', 'Passion Fruit', 'Mango', 'Products'], 'requiredItems': { 'Plain yogurt': 1, 'Raspberry': 4, 'Passion Fruit': 1, 'Mango': 2 } },
    "Bacon pie": { 'price': 219.6, 'level': 18, 'categories': ['Pie Oven', 'Wheat', 'Egg', 'Bacon', 'Products'], 'requiredItems': { 'Wheat': 2, 'Bacon': 3, 'Egg': 1 } },
    "Goat cheese": { 'price': 162.0, 'level': 33, 'categories': ['Dairy', 'Goat Milk', 'Products'], 'requiredItems': { 'Goat Milk': 2 } },
    "Carrot juice": { 'price': 46.8, 'level': 26, 'categories': ['Juice Press', 'Carrot', 'Products'], 'requiredItems': { 'Carrot': 3 } },
    "Brown sugar": { 'price': 32.4, 'level': 7, 'categories': ['Sugar Mill', 'Sugarcane', 'Products'], 'requiredItems': { 'Sugarcane': 1 } },
    "Nachos": { 'price': 432.0, 'level': 87, 'categories': ['Taco Kitchen', 'Corn', 'Cheese', 'Salsa', 'Products'], 'requiredItems': { 'Cheese': 1, 'Corn': 4, 'Salsa': 1 } },
    "Bracelet": { 'price': 514.8, 'level': 38, 'categories': ['Jeweler', 'Silver Bar', 'Gold Bar', 'Products'], 'requiredItems': { 'Silver bar': 2, 'Gold bar': 1 } },
    "Beetroot salad": { 'price': 234.0, 'level': 76, 'categories': ['Salad Bar', 'Beetroot', 'Goat Cheese', 'Products'], 'requiredItems': { 'Beetroot': 3, 'Goat cheese': 1 } },
    "Berry smoothie": { 'price': 547.2, 'level': 64, 'categories': ['Smoothie Mixer', 'Raspberry', 'Blackberry', 'Strawberry', 'Products'], 'requiredItems': { 'Raspberry': 3, 'Strawberry': 3, 'Blackberry': 3 } },
    "Silver bar": { 'price': 147.6, 'level': 24, 'categories': ['Smelters', 'Silver Ore', 'Products'], 'requiredItems': { 'Silver ore': 3 } },
    "Chocolate fondue": { 'price': 626.4, 'level': 81, 'categories': ['Fondue Pot', 'Strawberry', 'Chocolate', 'Products'], 'requiredItems': { 'Chocolate': 1, 'Strawberry': 3 } },
    "Tomato sauce": { 'price': 230.4, 'level': 69, 'categories': ['Sauce Maker', 'Brown Sugar', 'Tomato', 'Lemon', 'Products'], 'requiredItems': { 'Brown sugar': 1, 'Lemon': 1, 'Tomato': 2 } },
    "Pillow": { 'price': 676.8, 'level': 51, 'categories': ['Sewing Machine', 'Cotton Fabric', 'Duck Feather', 'Products'], 'requiredItems': { 'Cotton fabric': 2, 'Duck Feather': 3 } },
    "Blackberry jam": { 'price': 388.8, 'level': 37, 'categories': ['Jam Maker', 'Blackberry', 'Products'], 'requiredItems': { 'Blackberry': 3 } },
    "Crunchy donut": { 'price': 594.0, 'level': 82, 'categories': ['Donut Maker', 'Plain Donut', 'Cacao', 'Peanuts', 'Products'], 'requiredItems': { 'Plain donut': 1, 'Cacao': 1 } },
    "Chocolate cake": { 'price': 320.4, 'level': 36, 'categories': ['Cake Oven', 'Brown Sugar', 'Butter', 'Cacao', 'Products'], 'requiredItems': { 'Cacao': 2, 'Brown sugar': 1, 'Butter': 1 } },
    "Pumpkin pie": { 'price': 158.4, 'level': 15, 'categories': ['Pie Oven', 'Wheat', 'Egg', 'Pumpkin', 'Products'], 'requiredItems': { 'Pumpkin': 3, 'Wheat': 2, 'Egg': 1 } },
    "Potato soup": { 'price': 255.6, 'level': 78, 'categories': ['Soup Kitchen', 'Milk', 'Potato', 'Onion', 'Products'], 'requiredItems': { 'Potato': 3, 'Onion': 2, 'Milk': 1 } },
    "Butter": { 'price': 82.8, 'level': 9, 'categories': ['Dairy', 'Milk', 'Products'], 'requiredItems': { 'Milk': 2 } },
    "Lemon pie": { 'price': 446.4, 'level': 67, 'categories': ['Pie Oven', 'Wheat', 'Egg', 'Lemon Curd', 'Products'], 'requiredItems': { 'Lemon curd': 1, 'Wheat': 2, 'Egg': 1 } },
    "Coconut ice cream": { 'price': 320.4, 'level': 102, 'categories': ['Ice Cream Maker', 'Coconut', 'Syrup', 'Products'], 'requiredItems': { 'Coconut': 2, 'Syrup': 1 } },
    "Mushroom pasta": { 'price': 280.8, 'level': 101, 'categories': ['Pasta Kitchen', 'Mushroom', 'Goat Milk', 'Fresh Pasta', 'Products'], 'requiredItems': { 'Mushroom': 5, 'Fresh pasta': 3, 'Goat Milk': 1 } },
    "Pancake": { 'price': 108.0, 'level': 9, 'categories': ['BBQ Grill', 'Egg', 'Brown Sugar', 'Products'], 'requiredItems': { 'Egg': 3, 'Brown sugar': 1 } },
    "Breakfast waffles": { 'price': 424.8, 'level': 119, 'categories': ['Waffle Maker', 'Plain Waffles', 'Bacon', 'Egg', 'Asparagus', 'Products'], 'requiredItems': { 'Plain waffles': 1, 'Bacon': 2, 'Egg': 1, 'Asparagus': 2 } },
    "Iron ore": { 'price': 14.4, 'level': 34, 'categories': ['Mine', 'Products'], 'requiredItems': { 'Dynamite': 2, 'TNT Barrel': 3, 'Shovel': 4, 'Pickaxe': 5 } },
    "Pasta carbonara": { 'price': 410.4, 'level': 83, 'categories': ['Pasta Kitchen', 'Egg', 'Bacon', 'Cheese', 'Fresh Pasta', 'Products'], 'requiredItems': { 'Fresh pasta': 3, 'Bacon': 2, 'Egg': 1, 'Cheese': 1 } },
    "Onion dog": { 'price': 306.0, 'level': 80, 'categories': ['Hot Dog Stand', 'Bread', 'Chili Pepper', 'Bacon', 'Onion', 'Products'], 'requiredItems': { 'Bacon': 2, 'Bread': 1, 'Chili Pepper': 1, 'Onion': 3 } },
    "Lemon candle": { 'price': 457.2, 'level': 72, 'categories': ['Candle Maker', 'Beeswax', 'Lemon', 'Products'], 'requiredItems': { 'Beeswax': 1, 'Lemon': 2 } },
    "Guava cupcake": { 'price': 583.2, 'level': 109, 'categories': ['Cupcake Maker', 'Plain Cupcake', 'Guava', 'Cream', 'Products'], 'requiredItems': { 'Plain cupcake': 1, 'Guava': 2, 'Cream': 1 } },
    "Frutti di mare pizza": { 'price': 403.2, 'level': 45, 'categories': ['Bakery', 'Wheat', 'Cheese', 'Fish Fillet', 'Lobster Tail', 'Products'], 'requiredItems': { 'Wheat': 2, 'Fish Fillet': 1, 'Lobster Tail': 1, 'Cheese': 1 } },
    "Green tea": { 'price': 241.2, 'level': 80, 'categories': ['Tea Stand', 'Tea Leaf', 'Products'], 'requiredItems': { 'Tea Leaf': 5 } },
    "Bacon donut": { 'price': 388.8, 'level': 88, 'categories': ['Donut Maker', 'Plain Donut', 'Bacon', 'Syrup', 'Products'], 'requiredItems': { 'Plain donut': 3, 'Bacon': 1 } },
    "Floral candle": { 'price': 442.8, 'level': 95, 'categories': ['Candle Maker', 'Indigo', 'Beeswax', 'Peony', 'Sunflower', 'Products'], 'requiredItems': { 'Beeswax': 1, 'Peony': 2, 'Sunflower': 2, 'Indigo': 2 } },
    "Mushroom Salad": { 'price': 216.0, 'level': 89, 'categories': ['Salad Bar', 'Bacon', 'Potato', 'Lettuce', 'Mushroom', 'Products'], 'requiredItems': { 'Mushroom': 3, 'Lettuce': 1, 'Potato': 2, 'Bacon': 1 } },
    "Filled donut": { 'price': 403.2, 'level': 93, 'categories': ['Donut Maker', 'Plain Donut', 'Raspberry Jam', 'Products'], 'requiredItems': { 'Plain donut': 1, 'Raspberry jam': 1 } },
    "Olive dip": { 'price': 468.0, 'level': 66, 'categories': ['Sauce Maker', 'Bread', 'Fish Fillet', 'Olive', 'Lemon', 'Products'], 'requiredItems': { 'Olive': 3, 'Bread': 2, 'Fish Fillet': 1, 'Lemon': 1 } },
    "Gracious bouquet": { 'price': 500.4, 'level': 73, 'categories': ['Flower Shop', 'Cotton Fabric', 'Gold Ore', 'Diamond', 'Lily', 'Products'], 'requiredItems': { 'Cotton fabric': 1, 'Lily': 5, 'Gold ore': 1, 'Diamond': 1 } },
    "Rustic bouquet": { 'price': 208.8, 'level': 49, 'categories': ['Flower Shop', 'Wheat', 'Indigo', 'Cotton', 'Products'], 'requiredItems': { 'Wheat': 5, 'Indigo': 3, 'Cotton': 3 } },
    "Lemon curd": { 'price': 378.0, 'level': 66, 'categories': ['Sauce Maker', 'Egg', 'Butter', 'White Sugar', 'Lemon', 'Products'], 'requiredItems': { 'Lemon': 2, 'Butter': 1, 'Egg': 2, 'White sugar': 1 } },
    "Black sesame smoothie": { 'price': 313.2, 'level': 93, 'categories': ['Smoothie Mixer', 'Goat Milk', 'Sesame', 'Banana', 'Products'], 'requiredItems': { 'Sesame': 3, 'Banana': 1, 'Goat Milk': 2 } },
    "Chili poppers": { 'price': 406.8, 'level': 98, 'categories': ['Deep Fryer', 'Chili Pepper', 'Wheat', 'Bacon', 'Cheese', 'Products'], 'requiredItems': { 'Chili Pepper': 3, 'Wheat': 1, 'Bacon': 3, 'Cheese': 1 } },
    "Cherry jam": { 'price': 334.8, 'level': 38, 'categories': ['Jam Maker', 'Cherry', 'Products'], 'requiredItems': { 'Cherry': 3 } },
    "Sweater": { 'price': 151.2, 'level': 17, 'categories': ['Loom', 'Wool', 'Products'], 'requiredItems': { 'Wool': 2 } },
    "Peach tart": { 'price': 435.6, 'level': 76, 'categories': ['Pie Oven', 'Wheat', 'Egg', 'Cream', 'Peach', 'Products'], 'requiredItems': { 'Cream': 1, 'Egg': 2, 'Peach': 3, 'Wheat': 2 } },
    "Caramel latte": { 'price': 345.6, 'level': 62, 'categories': ['Coffee Kiosk', 'Milk', 'Coffee Bean', 'Toffee', 'Products'], 'requiredItems': { 'Coffee Bean': 2, 'Toffee': 1, 'Milk': 1 } },
    "Gold ore": { 'price': 21.6, 'level': 24, 'categories': ['Mine', 'Products'], 'requiredItems': { 'Dynamite': 2, 'TNT Barrel': 3, 'Shovel': 4, 'Pickaxe': 5 } },
    "Winter stew": { 'price': 295.2, 'level': 112, 'categories': ['Stew Pot', 'Potato', 'Bacon', 'Onion', 'Mushroom', 'Products'], 'requiredItems': { 'Bacon': 1, 'Potato': 3, 'Onion': 2, 'Mushroom': 2 } },
    "Soft bouquet": { 'price': 298.8, 'level': 93, 'categories': ['Flower Shop', 'Cotton', 'Cotton Fabric', 'Peony', 'Products'], 'requiredItems': { 'Peony': 4, 'Cotton': 1, 'Cotton fabric': 1 } },
    "Peanut fudge": { 'price': 1141.2, 'level': 111, 'categories': ['Fudge Shop', 'Butter', 'Cacao', 'White Sugar', 'Peanuts', 'Products'], 'requiredItems': { 'Butter': 2, 'Cacao': 2, 'White sugar': 1, 'Peanuts': 2 } },
    "Sesame Ice Cream": { 'price': 176.4, 'level': 50, 'categories': ['Ice Cream Maker', 'Cream', 'Brown Sugar', 'Sesame', 'Products'], 'requiredItems': { 'Cream': 1, 'Sesame': 3, 'Brown sugar': 1 } },
    "Tropical fondue": { 'price': 417.6, 'level': 100, 'categories': ['Fondue Pot', 'White Sugar', 'Cream', 'Pineapple', 'Mango', 'Products'], 'requiredItems': { 'White sugar': 1, 'Cream': 2, 'Pineapple': 3, 'Mango': 2 } },
    "Apple jam": { 'price': 219.6, 'level': 35, 'categories': ['Jam Maker', 'Apple', 'Products'], 'requiredItems': { 'Apple': 3 } },
    "Cow feed": { 'price': 14.4, 'level': 6, 'categories': ['Feed Mill', 'Corn', 'Soybean', 'Products'], 'requiredItems': { 'Soybean': 2, 'Corn': 1 } },
    "Banana pancakes": { 'price': 352.8, 'level': 94, 'categories': ['BBQ Grill', 'Wheat', 'Cream', 'Blackberry', 'Banana', 'Products'], 'requiredItems': { 'Banana': 1, 'Blackberry': 2, 'Wheat': 3, 'Cream': 1 } },
    "Milk tea": { 'price': 190.8, 'level': 81, 'categories': ['Tea Stand', 'Milk', 'Tea Leaf', 'Products'], 'requiredItems': { 'Milk': 1, 'Tea Leaf': 3 } },
    "Colorful candles": { 'price': 324.0, 'level': 84, 'categories': ['Note', 'Candle Maker', 'Beeswax', 'Raspberry', 'Carrot', 'Products'], 'requiredItems': { 'Beeswax': 1, 'Raspberry': 1 } },
    "Wooly chaps": { 'price': 309.6, 'level': 21, 'categories': ['Note', 'Sewing Machine', 'Wool', 'Cotton Fabric', 'Products'], 'requiredItems': { 'Cotton fabric': 1, 'Wool': 3 } },
    "Potato Omelet": { 'price': 270.0, 'level': 87, 'categories': ['New', 'Omelet Station', 'Egg', 'Potato', 'Bacon', 'Products'], 'requiredItems': { 'Egg': 3, 'Potato': 1, 'Bacon': 3 } },
    "Chocolate ice cream": { 'price': 342.0, 'level': 39, 'categories': ['Ice Cream Maker', 'Milk', 'Cream', 'White Sugar', 'Cacao', 'Products'], 'requiredItems': { 'Cream': 1, 'White sugar': 1, 'Cacao': 2, 'Milk': 1 } },
    "Mint ice cream": { 'price': 288.0, 'level': 85, 'categories': ['Ice Cream Maker', 'Cream', 'White Sugar', 'Cacao', 'Mint', 'Products'], 'requiredItems': { 'Cream': 1, 'White sugar': 1, 'Mint': 2, 'Cacao': 1 } },
    "Apple juice": { 'price': 129.6, 'level': 28, 'categories': ['Juice Press', 'Apple', 'Products'], 'requiredItems': { 'Apple': 2 } },
    "Feta salad": { 'price': 745.2, 'level': 58, 'categories': ['Salad Bar', 'Roasted Tomatoes', 'Goat Cheese', 'Olive', 'Lettuce', 'Products'], 'requiredItems': { 'Lettuce': 3, 'Roasted tomatoes': 1, 'Goat cheese': 2, 'Olive': 2 } },
    "Meat Bucket": { 'price': 72.0, 'level': 0, 'categories': [], 'requiredItems': { 'Fish Fillet': 3, 'Carrot': 5 } },
    "Refined coal": { 'price': 108.0, 'level': 33, 'categories': ['Smelters', 'Coal', 'Products'], 'requiredItems': { 'Coal': 3 } },
    "Canned fish": { 'price': 471.6, 'level': 95, 'categories': ['Preservation Station', 'Fish Fillet', 'Chili Pepper', 'Olive Oil', 'Products'], 'requiredItems': { 'Fish Fillet': 2, 'Chili Pepper': 1, 'Olive oil': 1 } },
    "Mint fudge": { 'price': 522.0, 'level': 102, 'categories': ['Fudge Shop', 'Butter', 'Cacao', 'White Sugar', 'Mint', 'Products'], 'requiredItems': { 'Cabbage': 2, 'Cacao': 2, 'White sugar': 1, 'Mint': 3 } },
    "Syrup": { 'price': 90.0, 'level': 18, 'categories': ['Sugar Mill', 'Sugarcane', 'Products'], 'requiredItems': { 'Sugarcane': 4 } },
    "Plum jam": { 'price': 385.2, 'level': 94, 'categories': ['Jam Maker', 'Plum', 'Products'], 'requiredItems': { 'Plum': 3 } },
    "Seafood salad": { 'price': 763.2, 'level': 64, 'categories': ['Salad Bar', 'Fish Fillet', 'Lobster Tail', 'Lettuce', 'Mayonnaise', 'Products'], 'requiredItems': { 'Lettuce': 3, 'Fish Fillet': 1, 'Lobster Tail': 1, 'Mayonnaise': 1 } },
    "Garlic bread": { 'price': 198.0, 'level': 60, 'categories': ['BBQ Grill', 'Bread', 'Butter', 'Garlic', 'Products'], 'requiredItems': { 'Bread': 2, 'Butter': 1, 'Garlic': 4 } },
    "Orange sorbet": { 'price': 399.6, 'level': 78, 'categories': ['Ice Cream Maker', 'Honey', 'Orange', 'Products'], 'requiredItems': { 'Honey': 1, 'Orange': 2 } },
    "Fresh pasta": { 'price': 43.2, 'level': 67, 'categories': ['Pasta Maker', 'Wheat', 'Egg', 'Products'], 'requiredItems': { 'Egg': 1, 'Wheat': 2 } },
    "Rich fudge": { 'price': 644.4, 'level': 99, 'categories': ['Fudge Shop', 'Butter', 'Cacao', 'White Sugar', 'Products'], 'requiredItems': { 'Butter': 3, 'Cacao': 3, 'White sugar': 2 } },
    "Blue woolly hat": { 'price': 111.6, 'level': 19, 'categories': ['Note', 'Loom', 'Indigo', 'Wool', 'Products'], 'requiredItems': { 'Wool': 1, 'Indigo': 1 } },
    "Blue sweater": { 'price': 208.8, 'level': 20, 'categories': ['Loom', 'Indigo', 'Wool', 'Products'], 'requiredItems': { 'Wool': 2, 'Indigo': 2 } },
    "Raspberry jam": { 'price': 252.0, 'level': 36, 'categories': ['Jam Maker', 'Raspberry', 'Products'], 'requiredItems': { 'Raspberry': 3 } },
    "Platinum Ore": { 'price': 32.4, 'level': 24, 'categories': ['Mine', 'Products'], 'requiredItems': { 'Dynamite': 2, 'TNT Barrel': 3, 'Shovel': 4, 'Pickaxe': 5 } },
    "Fruit sorbet": { 'price': 518.4, 'level': 106, 'categories': ['Ice Cream Maker', 'Guava', 'Passion Fruit', 'Mango', 'White Sugar', 'Products'], 'requiredItems': { 'Guava': 1, 'Passion Fruit': 1, 'Mango': 2, 'White sugar': 3 } },
    "Blackberry muffin": { 'price': 226.8, 'level': 26, 'categories': ['Bakery', 'Wheat', 'Blackberry', 'Egg', 'Products'], 'requiredItems': { 'Wheat': 1, 'Egg': 2, 'Blackberry': 2 } },
    "Chocolate": { 'price': 460.8, 'level': 54, 'categories': ['Candy Machine', 'Cream', 'White Sugar', 'Cacao', 'Products'], 'requiredItems': { 'Cacao': 3, 'Cream': 1, 'White sugar': 1 } },
    "Mint essential oil": { 'price': 172.8, 'level': 85, 'categories': ['New', 'Essential Oils Lab', 'Mint', 'Products'], 'requiredItems': { 'Mint': 5 } },
    "Cotton fabric": { 'price': 108.0, 'level': 18, 'categories': ['Loom', 'Cotton', 'Products'], 'requiredItems': { 'Cotton': 3 } },
    "Rich soap": { 'price': 266.4, 'level': 121, 'categories': ['Bath Kiosk', 'Oats', 'Pomegranate', 'Coconut', 'Products'], 'requiredItems': { 'Oats': 2, 'Pomegranate': 1, 'Coconut': 1 } },
    "Sprinkled donut": { 'price': 313.2, 'level': 79, 'categories': ['Donut Maker', 'Plain Donut', 'Cacao', 'Products'], 'requiredItems': { 'Plain donut': 1, 'Cacao': 2 } },
    "Lobster pasta": { 'price': 637.2, 'level': 79, 'categories': ['Pasta Kitchen', 'Cream', 'Tomato', 'Lobster Tail', 'Fresh Pasta', 'Products'], 'requiredItems': { 'Lobster Tail': 1, 'Cream': 2, 'Fresh pasta': 3, 'Tomato': 4 } },
    "Chili fudge": { 'price': 540.0, 'level': 104, 'categories': ['Fudge Shop', 'Butter', 'Cacao', 'White Sugar', 'Chili Pepper', 'Products'], 'requiredItems': { 'Cabbage': 2, 'Cacao': 2, 'White sugar': 1, 'Chili Pepper': 3 } },
    "Cream donut": { 'price': 230.4, 'level': 86, 'categories': ['Donut Maker', 'Plain Donut', 'Cream', 'Brown Sugar', 'Products'], 'requiredItems': { 'Plain donut': 1, 'Cream': 1 } },
    "Fish soup": { 'price': 298.8, 'level': 53, 'categories': ['Soup Kitchen', 'Milk', 'Carrot', 'Fish Fillet', 'Potato', 'Products'], 'requiredItems': { 'Potato': 3, 'Fish Fillet': 2, 'Milk': 1, 'Carrot': 1 } },
    "Eggplant parmesan": { 'price': 442.8, 'level': 99, 'categories': ['Pie Oven', 'Cheese', 'Eggplant', 'Tomato Sauce', 'Products'], 'requiredItems': { 'Eggplant': 4, 'Cheese': 1, 'Tomato sauce': 1 } },
    "Beeswax": { 'price': 234.0, 'level': 48, 'categories': ['Honey Extractor', 'Honeycomb', 'Products'], 'requiredItems': { 'Honeycomb': 3 } },
    "Grilled Asparagus": { 'price': 486.0, 'level': 67, 'categories': ['BBQ Grill', 'Bacon', 'Lemon', 'Asparagus', 'Products'], 'requiredItems': { 'Asparagus': 5, 'Bacon': 3, 'Lemon': 1 } },
    "Strawberry ice cream": { 'price': 331.2, 'level': 34, 'categories': ['Ice Cream Maker', 'Milk', 'White Sugar', 'Strawberry', 'Cream', 'Products'], 'requiredItems': { 'Cream': 1, 'White sugar': 1, 'Strawberry': 3, 'Milk': 1 } },
    "Iron bracelet": { 'price': 658.8, 'level': 41, 'categories': ['Jeweler', 'Silver Bar', 'Refined Coal', 'Iron Bar', 'Products'], 'requiredItems': { 'Silver bar': 1, 'Refined coal': 2, 'Iron bar': 2 } },
    "Bacon fondue": { 'price': 507.6, 'level': 86, 'categories': ['Fondue Pot', 'Bacon', 'Olive Oil', 'Broccoli', 'Bell Pepper', 'Products'], 'requiredItems': { 'Bacon': 3, 'Broccoli': 1, 'Bell Pepper': 1, 'Olive oil': 1 } },
    "Lobster sushi": { 'price': 637.2, 'level': 59, 'categories': ['Sushi Bar', 'Lobster Tail', 'Soy Sauce', 'Rice', 'Products'], 'requiredItems': { 'Lobster Tail': 1, 'Rice': 15, 'Soy sauce': 1 } },
    "Buttered popcorn": { 'price': 126.0, 'level': 16, 'categories': ['Popcorn Pot', 'Corn', 'Butter', 'Products'], 'requiredItems': { 'Corn': 2, 'Butter': 1 } },
    "Fried rice": { 'price': 205.2, 'level': 69, 'categories': ['Wok Kitchen', 'Egg', 'Rice', 'Products'], 'requiredItems': { 'Rice': 5, 'Egg': 5 } },
    "Corn bread": { 'price': 72.0, 'level': 7, 'categories': ['Bakery', 'Egg', 'Corn', 'Products'], 'requiredItems': { 'Corn': 2, 'Egg': 2 } },
    "Potato feta cake": { 'price': 309.6, 'level': 38, 'categories': ['Cake Oven', 'Egg', 'Goat Cheese', 'Potato', 'Products'], 'requiredItems': { 'Potato': 1, 'Egg': 4, 'Goat cheese': 1 } },
    "Grilled eggplant": { 'price': 324.0, 'level': 90, 'categories': ['BBQ Grill', 'Eggplant', 'Salsa', 'Products'], 'requiredItems': { 'Eggplant': 3, 'Salsa': 1 } },
    "Gingerbread cookie": { 'price': 273.6, 'level': 86, 'categories': ['Bakery', 'Wheat', 'Butter', 'Syrup', 'Ginger', 'Products'], 'requiredItems': { 'Wheat': 5, 'Butter': 1, 'Syrup': 1, 'Ginger': 2 } },
    "Fruity milkshake": { 'price': 759.6, 'level': 126, 'categories': ['New', 'Milkshake Bar', 'Peach Ice Cream', 'Orange', 'Lemon', 'Products'], 'requiredItems': { 'Peach ice cream': 1, 'Orange': 2, 'Lemon': 1 } },
    "Casserole": { 'price': 367.2, 'level': 36, 'categories': ['Pie Oven', 'Egg', 'Bacon', 'Cheese', 'Potato', 'Products'], 'requiredItems': { 'Potato': 2, 'Bacon': 2, 'Egg': 2, 'Cheese': 1 } },
    "Chocolate pie": { 'price': 514.8, 'level': 65, 'categories': ['Pie Oven', 'Wheat', 'Cacao', 'Egg', 'Peanuts', 'Products'], 'requiredItems': { 'Wheat': 3, 'Cacao': 2, 'Egg': 1, 'Peanuts': 1 } },
    "BLT salad": { 'price': 723.6, 'level': 62, 'categories': ['Salad Bar', 'Bacon', 'Roasted Tomatoes', 'Lettuce', 'Mayonnaise', 'Products'], 'requiredItems': { 'Lettuce': 3, 'Roasted tomatoes': 1, 'Bacon': 2, 'Mayonnaise': 1 } },
    "Honey": { 'price': 154.8, 'level': 39, 'categories': ['Honey Extractor', 'Honeycomb', 'Products'], 'requiredItems': { 'Honeycomb': 2 } },
    "Berry waffles": { 'price': 604.8, 'level': 114, 'categories': ['Waffle Maker', 'Plain Waffles', 'Syrup', 'Raspberry', 'Blackberry', 'Products'], 'requiredItems': { 'Plain waffles': 1, 'Syrup': 1, 'Raspberry': 3, 'Blackberry': 2 } },
    "Potato bread": { 'price': 284.4, 'level': 39, 'categories': ['Bakery', 'Egg', 'Butter', 'White Sugar', 'Potato', 'Products'], 'requiredItems': { 'Potato': 2, 'White sugar': 1, 'Egg': 3, 'Butter': 1 } },
    "Raspberry candle": { 'price': 360.0, 'level': 52, 'categories': ['Candle Maker', 'Raspberry', 'Beeswax', 'Products'], 'requiredItems': { 'Beeswax': 1, 'Raspberry': 2 } },
    "Plum smoothie": { 'price': 522.0, 'level': 102, 'categories': ['Smoothie Mixer', 'Honey', 'Plum', 'Grapes', 'Mint', 'Products'], 'requiredItems': { 'Plum': 3, 'Grapes': 2, 'Mint': 1, 'Honey': 1 } },
    "Berry juice": { 'price': 205.2, 'level': 31, 'categories': ['Juice Press', 'Raspberry', 'Blackberry', 'Products'], 'requiredItems': { 'Blackberry': 1, 'Raspberry': 1 } },
    "Honey face mask": { 'price': 320.4, 'level': 99, 'categories': ['Bath Kiosk', 'Lemon', 'Egg', 'Honey', 'Products'], 'requiredItems': { 'Egg': 2, 'Honey': 1, 'Lemon': 1 } },
    "Chicken feed": { 'price': 7.2, 'level': 3, 'categories': ['Feed Mill', 'Wheat', 'Corn', 'Products'], 'requiredItems': { 'Wheat': 2, 'Corn': 1 } },
    "Caramel apple": { 'price': 255.6, 'level': 51, 'categories': ['Candy Machine', 'Apple', 'Syrup', 'Products'], 'requiredItems': { 'Syrup': 2, 'Apple': 1 } },
    "Orange tea": { 'price': 255.6, 'level': 89, 'categories': ['Tea Stand', 'Orange', 'Tea Leaf', 'Products'], 'requiredItems': { 'Orange': 1, 'Tea Leaf': 3 } },
    "Sun hat": { 'price': 558.0, 'level': 74, 'categories': ['Hat Maker', 'Indigo', 'Wool', 'Raspberry', 'Duck Feather', 'Products'], 'requiredItems': { 'Wool': 3, 'Indigo': 1, 'Duck Feather': 2, 'Raspberry': 1 } },
    "Veggie lasagna": { 'price': 532.8, 'level': 74, 'categories': ['Pasta Kitchen', 'Carrot', 'Cheese', 'Tomato Sauce', 'Fresh Pasta', 'Products'], 'requiredItems': { 'Carrot': 1, 'Cheese': 1, 'Tomato sauce': 1, 'Fresh pasta': 3 } },
    "Platinum bar": { 'price': 205.2, 'level': 25, 'categories': ['Smelters', 'Platinum Ore', 'Products'], 'requiredItems': { 'Platinum Ore': 3 } },
    "Hand pies": { 'price': 295.2, 'level': 91, 'categories': ['Deep Fryer', 'Egg', 'Wheat', 'Apple Jam', 'Products'], 'requiredItems': { 'Apple jam': 1, 'Egg': 2, 'Wheat': 5 } },
    "Jelly beans": { 'price': 684.0, 'level': 60, 'categories': ['Candy Machine', 'White Sugar', 'Raspberry Jam', 'Blackberry Jam', 'Products'], 'requiredItems': { 'Blackberry jam': 1, 'Raspberry jam': 1, 'White sugar': 1 } },
    "Big sushi roll": { 'price': 648.0, 'level': 76, 'categories': ['Sushi Bar', 'Egg', 'Fish Fillet', 'Rice', 'Lettuce', 'Products'], 'requiredItems': { 'Fish Fillet': 1, 'Rice': 20, 'Egg': 3, 'Lettuce': 5 } },
    "Kimchi": { 'price': 219.6, 'level': 98, 'categories': ['Preservation Station', 'Cabbage', 'Ginger', 'Chili Pepper', 'Garlic', 'Products'], 'requiredItems': { 'Cabbage': 5, 'Ginger': 1, 'Chili Pepper': 1, 'Garlic': 1 } },
    "Macaroon": { 'price': 421.2, 'level': 101, 'categories': ['Bakery', 'Cacao', 'Coconut', 'White Sugar', 'Products'], 'requiredItems': { 'Cacao': 1, 'Coconut': 2, 'White sugar': 2 } },
    "Dried fruit": { 'price': 266.4, 'level': 102, 'categories': ['Preservation Station', 'Grapes', 'Raspberry', 'Strawberry', 'Orange', 'Products'], 'requiredItems': { 'Grapes': 1, 'Raspberry': 1, 'Strawberry': 1, 'Orange': 1 } },
    "Iron bar": { 'price': 129.6, 'level': 34, 'categories': ['Smelters', 'Iron Ore', 'Products'], 'requiredItems': { 'Iron ore': 3 } },
    "Cheese": { 'price': 122.4, 'level': 12, 'categories': ['Dairy', 'Milk', 'Products'], 'requiredItems': { 'Milk': 3 } },
    "Banana bread": { 'price': 424.8, 'level': 91, 'categories': ['Bakery', 'Wheat', 'Egg', 'Banana', 'Grapes', 'Products'], 'requiredItems': { 'Banana': 3, 'Grapes': 2, 'Wheat': 3, 'Egg': 1 } },
    "Bread": { 'price': 21.6, 'level': 2, 'categories': ['Bakery', 'Wheat', 'Products'], 'requiredItems': { 'Wheat': 3 } },
    "Birthday bouquet": { 'price': 349.2, 'level': 92, 'categories': ['Flower Shop', 'Cherry Juice', 'Peony', 'Lily', 'Indigo', 'Products'], 'requiredItems': { 'Cherry juice': 3, 'Peony': 1 } },
    "White sugar": { 'price': 50.4, 'level': 13, 'categories': ['Sugar Mill', 'Sugarcane', 'Products'], 'requiredItems': { 'Sugarcane': 2 } },
    "Quesadilla": { 'price': 241.2, 'level': 82, 'categories': ['Taco Kitchen', 'Wheat', 'Cheese', 'Chili Pepper', 'Products'], 'requiredItems': { 'Cheese': 1, 'Chili Pepper': 2, 'Wheat': 4 } },
    "Cocoa smoothie": { 'price': 511.2, 'level': 100, 'categories': ['Smoothie Mixer', 'Milk', 'Cacao', 'Banana', 'Products'], 'requiredItems': { 'Banana': 2, 'Cacao': 3, 'Milk': 1 } },
    "Hummus": { 'price': 277.2, 'level': 95, 'categories': ['Sauce Maker', 'Chickpea', 'Garlic', 'Lemon', 'Products'], 'requiredItems': { 'Chickpea': 3, 'Lemon': 2, 'Garlic': 1 } },
    "Sushi roll": { 'price': 489.6, 'level': 56, 'categories': ['Sushi Bar', 'Fish Fillet', 'Soy Sauce', 'Rice', 'Products'], 'requiredItems': { 'Fish Fillet': 1, 'Rice': 15, 'Soy sauce': 1 } },
    "Corn dog": { 'price': 529.2, 'level': 78, 'categories': ['Hot Dog Stand', 'Corn', 'Bacon', 'Olive Oil', 'Products'], 'requiredItems': { 'Bacon': 4, 'Corn': 4, 'Olive oil': 1 } },
    "Yogurt smoothie": { 'price': 349.2, 'level': 70, 'categories': ['Smoothie Mixer', 'Cream', 'White Sugar', 'Raspberry', 'Cherry', 'Products'], 'requiredItems': { 'Cream': 1, 'Raspberry': 2, 'Cherry': 1, 'White sugar': 1 } },
    "Cucumber smoothie": { 'price': 266.4, 'level': 70, 'categories': ['Smoothie Mixer', 'Honey', 'Pineapple', 'Cucumber', 'Products'], 'requiredItems': { 'Cucumber': 3, 'Honey': 1, 'Pineapple': 3 } },
    "Mocha milkshake": { 'price': 856.8, 'level': 125, 'categories': ['New', 'Milkshake Bar', 'Chocolate Ice Cream', 'Espresso', 'Products'], 'requiredItems': { 'Chocolate ice cream': 1, 'Espresso': 2 } },
    "Pineapple juice": { 'price': 68.4, 'level': 52, 'categories': ['Juice Press', 'Pineapple', 'Products'], 'requiredItems': { 'Pineapple': 3 } },
    "Bright bouquet": { 'price': 338.4, 'level': 65, 'categories': ['Flower Shop', 'Indigo', 'Cotton', 'Sunflower', 'Iron Ore', 'Products'], 'requiredItems': { 'Sunflower': 5, 'Indigo': 3, 'Cotton': 1, 'Iron ore': 5 } },
    "Cheese fondue": { 'price': 493.2, 'level': 91, 'categories': ['Fondue Pot', 'Cheese', 'Tomato', 'Potato Bread', 'Mushroom', 'Products'], 'requiredItems': { 'Potato bread': 1, 'Cheese': 1, 'Mushroom': 2, 'Tomato': 1 } },
    "Grape juice": { 'price': 104.4, 'level': 84, 'categories': ['Juice Press', 'Grapes', 'Products'], 'requiredItems': { 'Grapes': 2 } },
    "Pasta salad": { 'price': 759.6, 'level': 67, 'categories': ['Salad Bar', 'Tomato', 'Olive Oil', 'Lemon', 'Fresh Pasta', 'Products'], 'requiredItems': { 'Fresh pasta': 4, 'Lemon': 2, 'Olive oil': 1, 'Tomato': 2 } },
    "Necklace": { 'price': 727.2, 'level': 39, 'categories': ['Jeweler', 'Silver Bar', 'Gold Bar', 'Platinum Bar', 'Products'], 'requiredItems': { 'Silver bar': 2, 'Gold bar': 1, 'Platinum bar': 1 } },
    "Broccoli soup": { 'price': 237.6, 'level': 87, 'categories': ['Soup Kitchen', 'Potato', 'Broccoli', 'Onion', 'Products'], 'requiredItems': { 'Broccoli': 3, 'Onion': 1, 'Potato': 3 } },
    "Olive oil": { 'price': 277.2, 'level': 60, 'categories': ['Sauce Maker', 'Olive', 'Products'], 'requiredItems': { 'Olive': 3 } },
    "Lemon essential oil": { 'price': 288.0, 'level': 68, 'categories': ['New', 'Essential Oils Lab', 'Lemon', 'Products'], 'requiredItems': { 'Lemon': 3 } },
    "Honey popcorn": { 'price': 360.0, 'level': 40, 'categories': ['Popcorn Pot', 'Corn', 'Honey', 'Products'], 'requiredItems': { 'Corn': 2, 'Honey': 2 } },
    "Onion melt": { 'price': 417.6, 'level': 84, 'categories': ['Sandwich Bar', 'Corn Bread', 'Cheese', 'Onion', 'Products'], 'requiredItems': { 'Corn bread': 2, 'Onion': 3, 'Cheese': 1 } },
    "Lemon fudge": { 'price': 590.4, 'level': 108, 'categories': ['Fudge Shop', 'Butter', 'Milk', 'White Sugar', 'Lemon', 'Products'], 'requiredItems': { 'Butter': 2, 'White sugar': 2, 'Milk': 3, 'Lemon': 2 } },
    "Asparagus soup": { 'price': 255.6, 'level': 51, 'categories': ['Soup Kitchen', 'Asparagus', 'Cream', 'Products'], 'requiredItems': { 'Asparagus': 3, 'Cream': 2 } },
    "Fancy cake": { 'price': 450.0, 'level': 54, 'categories': ['Cake Oven', 'Raspberry', 'Cream Cake', 'Gold Ore', 'Lily', 'Products'], 'requiredItems': { 'Cream cake': 1, 'Lily': 3, 'Raspberry': 3, 'Gold ore': 1 } },
    "Broccoli pasta": { 'price': 345.6, 'level': 83, 'categories': ['Pasta Kitchen', 'Cheese', 'Broccoli', 'Fresh Pasta', 'Products'], 'requiredItems': { 'Broccoli': 3, 'Cheese': 1, 'Fresh pasta': 3 } },
    "Noodle soup": { 'price': 432.0, 'level': 73, 'categories': ['Soup Kitchen', 'Egg', 'Carrot', 'Chili Pepper', 'Rice Noodles', 'Products'], 'requiredItems': { 'Carrot': 2, 'Chili Pepper': 1, 'Egg': 2, 'Rice noodles': 3 } },
    "Raspberry muffin": { 'price': 140.4, 'level': 19, 'categories': ['Bakery', 'Wheat', 'Egg', 'Raspberry', 'Products'], 'requiredItems': { 'Wheat': 2, 'Egg': 1, 'Raspberry': 2 } },
    "Plain donut": { 'price': 129.6, 'level': 76, 'categories': ['Donut Maker', 'Milk', 'Egg', 'Wheat', 'White Sugar', 'Products'], 'requiredItems': { 'Milk': 1, 'White sugar': 1, 'Egg': 1, 'Wheat': 3 } },
    "Taco": { 'price': 396.0, 'level': 77, 'categories': ['Taco Kitchen', 'Corn Bread', 'Bacon', 'Salsa', 'Products'], 'requiredItems': { 'Corn bread': 1, 'Bacon': 1, 'Salsa': 1 } },
    "Roasted tomatoes": { 'price': 118.8, 'level': 30, 'categories': ['BBQ Grill', 'Tomato', 'Products'], 'requiredItems': { 'Tomato': 2 } },
    "Rice ball": { 'price': 464.4, 'level': 110, 'categories': ['Sushi Bar', 'Rice', 'Sesame', 'Plum', 'Products'], 'requiredItems': { 'Rice': 20, 'Sesame': 1, 'Plum': 1 } },
    "Affogato": { 'price': 435.6, 'level': 78, 'categories': ['Ice Cream Maker', 'Vanilla Ice Cream', 'Espresso', 'Products'], 'requiredItems': { 'Vanilla ice cream': 1, 'Espresso': 1 } },
    "Tofu dog": { 'price': 367.2, 'level': 76, 'categories': ['Hot Dog Stand', 'Soybean', 'Tomato', 'Lettuce', 'Products'], 'requiredItems': { 'Lettuce': 3, 'Soybean': 6, 'Tomato': 4 } },
    "Veggie bagel": { 'price': 532.8, 'level': 61, 'categories': ['Sandwich Bar', 'Bread', 'Tomato', 'Lettuce', 'Olive Oil', 'Products'], 'requiredItems': { 'Bread': 2, 'Tomato': 2, 'Lettuce': 3, 'Olive oil': 1 } },
    "Lemon lotion": { 'price': 403.2, 'level': 84, 'categories': ['Bath Kiosk', 'Lemon', 'Olive Oil', 'Products'], 'requiredItems': { 'Olive oil': 1, 'Lemon': 1 } },
    "Carrot pie": { 'price': 82.8, 'level': 14, 'categories': ['Pie Oven', 'Wheat', 'Egg', 'Carrot', 'Products'], 'requiredItems': { 'Carrot': 3, 'Wheat': 2, 'Egg': 1 } },
    "Rice": { 'price': 18.0, 'level': 56, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Goat Milk": { 'price': 64.8, 'level': 32, 'categories': ['Note', 'Animal Goods'], 'requiredItems': {} },
    "Eggplant": { 'price': 14.4, 'level': 90, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Bell Pepper": { 'price': 36.0, 'level': 74, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Cabbage": { 'price': 18.0, 'level': 65, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Ginger": { 'price': 28.8, 'level': 78, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Cherry": { 'price': 68.4, 'level': 22, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Guava": { 'price': 111.6, 'level': 104, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Fish Fillet": { 'price': 54.0, 'level': 27, 'categories': ['Animal Goods', 'Fishing'], 'requiredItems': {} },
    "Lemon": { 'price': 93.6, 'level': 66, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Bacon": { 'price': 50.4, 'level': 10, 'categories': ['Animal Goods'], 'requiredItems': {} },
    "Corn": { 'price': 7.2, 'level': 2, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Soybean": { 'price': 10.8, 'level': 5, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Pumpkin": { 'price': 32.4, 'level': 15, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Sesame": { 'price': 18.0, 'level': 50, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Pomegranate": { 'price': 111.6, 'level': 107, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Honeycomb": { 'price': 68.4, 'level': 39, 'categories': ['Animal Goods'], 'requiredItems': {} },
    "Clay": { 'price': 18.0, 'level': 94, 'categories': ['Note', 'Field Crops'], 'requiredItems': {} },
    "Chili Pepper": { 'price': 36.0, 'level': 25, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Lily": { 'price': 21.6, 'level': 53, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Asparagus": { 'price': 43.2, 'level': 49, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Cacao": { 'price': 86.4, 'level': 36, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Banana": { 'price': 104.4, 'level': 88, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Passion Fruit": { 'price': 18.0, 'level': 88, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Mango": { 'price': 100.8, 'level': 97, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Wool": { 'price': 54.0, 'level': 16, 'categories': ['Animal Goods'], 'requiredItems': {} },
    "Watermelon": { 'price': 39.6, 'level': 92, 'categories': ['Note', 'Field Crops'], 'requiredItems': {} },
    "Blackberry": { 'price': 82.8, 'level': 26, 'categories': ['Bush Crops'], 'requiredItems': {} },
    "Garlic": { 'price': 14.4, 'level': 60, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Grapes": { 'price': 32.4, 'level': 84, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Indigo": { 'price': 25.2, 'level': 13, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Plum": { 'price': 82.8, 'level': 94, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Strawberry": { 'price': 50.4, 'level': 34, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Olive": { 'price': 82.8, 'level': 57, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Oats": { 'price': 7.2, 'level': 119, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Tea Leaf": { 'price': 43.2, 'level': 80, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Egg": { 'price': 18.0, 'level': 1, 'categories': ['Animal Goods'], 'requiredItems': {} },
    "Peanuts": { 'price': 234.0, 'level': 62, 'categories': ['Animal Goods'], 'requiredItems': {} },
    "Cotton": { 'price': 28.8, 'level': 18, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Carrot": { 'price': 7.2, 'level': 9, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Coconut": { 'price': 108.0, 'level': 101, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Lobster Tail": { 'price': 201.6, 'level': 44, 'categories': ['Animal Goods'], 'requiredItems': {} },
    "Chickpea": { 'price': 18.0, 'level': 95, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Mushroom": { 'price': 10.8, 'level': 89, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Cucumber": { 'price': 14.4, 'level': 70, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Raspberry": { 'price': 46.8, 'level': 19, 'categories': ['Bush Crops'], 'requiredItems': {} },
    "Peony": { 'price': 36.0, 'level': 82, 'categories': ['Note', 'Field Crops'], 'requiredItems': {} },
    "Wheat": { 'price': 3.6, 'level': 1, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Pineapple": { 'price': 14.4, 'level': 52, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Milk": { 'price': 32.4, 'level': 6, 'categories': ['Note', 'Animal Goods'], 'requiredItems': {} },
    "Duck Feather": { 'price': 140.4, 'level': 50, 'categories': ['Animal Goods'], 'requiredItems': {} },
    "Sunflower": { 'price': 21.6, 'level': 63, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Beetroot": { 'price': 14.4, 'level': 72, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Coffee Bean": { 'price': 64.8, 'level': 42, 'categories': ['Bush Crops'], 'requiredItems': {} },
    "Mint": { 'price': 32.4, 'level': 85, 'categories': ['Note', 'Field Crops'], 'requiredItems': {} },
    "Orange": { 'price': 97.2, 'level': 71, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Onion": { 'price': 39.6, 'level': 68, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Apple": { 'price': 39.6, 'level': 15, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Tomato": { 'price': 43.2, 'level': 30, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Sugarcane": { 'price': 14.4, 'level': 7, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Broccoli": { 'price': 21.6, 'level': 83, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Peach": { 'price': 100.8, 'level': 76, 'categories': ['Tree Crops'], 'requiredItems': {} },
    "Lettuce": { 'price': 32.4, 'level': 58, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Potato": { 'price': 36.0, 'level': 35, 'categories': ['Field Crops'], 'requiredItems': {} },
    "Axe": { 'price': 36.0, 'level': 5, 'categories': ['Supplies'], 'requiredItems': {} },
    "Bolt": { 'price': 270.0, 'level': 1, 'categories': ['Supplies'], 'requiredItems': {} },
    "Brick": { 'price': 342.0, 'level': 34, 'categories': ['Supplies'], 'requiredItems': {} },
    "Duct Tape": { 'price': 270.0, 'level': 1, 'categories': ['Supplies'], 'requiredItems': {} },
    "Dynamite": { 'price': 25.0, 'level': 5, 'categories': ['Supplies'], 'requiredItems': {} },
    "Hammer": { 'price': 342.0, 'level': 34, 'categories': ['Supplies'], 'requiredItems': {} },
    "Hand Drill": { 'price': 342.0, 'level': 34, 'categories': ['Supplies'], 'requiredItems': {} },
    "Land Deed": { 'price': 403.0, 'level': 22, 'categories': ['Supplies', 'Expansion'], 'requiredItems': {} },
    "Mallet": { 'price': 403.0, 'level': 22, 'categories': ['Expansion', 'Supplies'], 'requiredItems': {} },
    "Map Piece": { 'price': 450.0, 'level': 34, 'categories': ['Expansion', 'Supplies'], 'requiredItems': {} },
    "Marker Stake": { 'price': 403.0, 'level': 22, 'categories': ['Expansion', 'Supplies'], 'requiredItems': {} },
    "Nail": { 'price': 270.0, 'level': 1, 'categories': ['Supplies'], 'requiredItems': {} },
    "Paint Bucket": { 'price': 342.0, 'level': 34, 'categories': ['Supplies'], 'requiredItems': {} },
    "Pickaxe": { 'price': 126.0, 'level': 34, 'categories': ['Supplies'], 'requiredItems': {} },
    "Plank": { 'price': 270.0, 'level': 1, 'categories': ['Supplies'], 'requiredItems': {} },
    "Saw": { 'price': 54.0, 'level': 5, 'categories': ['Supplies'], 'requiredItems': {} },
    "Screw": { 'price': 270.0, 'level': 1, 'categories': ['Supplies'], 'requiredItems': {} },
    "Shovel": { 'price': 108.0, 'level': 5, 'categories': ['Supplies'], 'requiredItems': {} },
    "Stone Block": { 'price': 342.0, 'level': 34, 'categories': ['Supplies'], 'requiredItems': {} },
    "Tar Bucket": { 'price': 342.0, 'level': 34, 'categories': ['Supplies'], 'requiredItems': {} },
    "TNT Barrel": { 'price': 72.0, 'level': 5, 'categories': ['Supplies'], 'requiredItems': {} },
    "Wood Panel": { 'price': 270.0, 'level': 1, 'categories': ['Supplies'], 'requiredItems': {} },
    "Help": { 'price': 100.0, 'level': 0, 'categories': [], 'requiredItems': {} },
    "Diamond": {'price': -1, 'level': 0, 'categories': [], 'requiredItems': {}}
} as { [key: string]: ItemInformation }

export default itemPrices
export type { ItemInformation }